#!/usr/bin/env python3
"""Build a standalone F2Z PCS interval dashboard.

The page combines two deliberately separate datasets:

* schema-version-3 clean headline measurements from
  ``scripts/export_pcs_tables.py``; and
* ``f2z.interval-data/v1`` traces from
  ``scripts/export_f2z_intervals.py``.

The interval timeline always uses real start/end geometry from a measured
representative run.  Existing output is replaced only when it carries this
generator's marker, unless ``--adopt-existing`` is used for the intentional
first replacement.
"""

from __future__ import annotations

import argparse
from html import escape as escape_html_text
import json
import math
import os
import sys
import tempfile
from copy import deepcopy
from pathlib import Path
from typing import Any


GENERATED_MARKER = (
    "<!-- GENERATED BY scripts/build_f2z_dashboard.py; DO NOT EDIT BY HAND. -->"
)
EXPECTED_EXPONENTS = list(range(20, 31))
INTERVAL_SCHEMA = "f2z.interval-data/v1"
TRACE_SCHEMA = "zkperf.trace/v1"
METRIC_KEYS = ("trial", "commit", "prove", "serialize", "verify")
PHASE_KEYS = (
    "pack_ms",
    "pow2_ms",
    "forest_core_ms",
    "fold_v_ms",
    "presum_tables_ms",
    "presum_run_ms",
    "rings_ms",
    "basis_combine_ms",
    "ligerito_recursive_ms",
    "untagged_ms",
)


class DashboardError(ValueError):
    """The input or requested output violates the dashboard contract."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="schema-version-3 dashboard-data.json with clean headline metrics",
    )
    parser.add_argument(
        "--interval-input",
        type=Path,
        required=True,
        help="f2z.interval-data/v1 JSON with real representative-run intervals",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="generated standalone HTML path",
    )
    parser.add_argument(
        "--adopt-existing",
        action="store_true",
        help=(
            "replace one existing regular HTML file that predates this generator; "
            "subsequent writes require the marker"
        ),
    )
    return parser.parse_args()


def require_mapping(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise DashboardError(f"{label} must be an object")
    return value


def require_list(value: Any, label: str) -> list[Any]:
    if not isinstance(value, list):
        raise DashboardError(f"{label} must be an array")
    return value


def require_text(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise DashboardError(f"{label} must be a non-empty string")
    return value


def require_bool(value: Any, label: str, expected: bool | None = None) -> bool:
    if not isinstance(value, bool):
        raise DashboardError(f"{label} must be boolean")
    if expected is not None and value is not expected:
        raise DashboardError(f"{label} must be {str(expected).lower()}")
    return value


def require_number(value: Any, label: str, *, positive: bool = False) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise DashboardError(f"{label} must be numeric")
    number = float(value)
    if not math.isfinite(number) or number < 0 or (positive and number <= 0):
        qualifier = "positive and " if positive else ""
        raise DashboardError(f"{label} must be {qualifier}finite")
    return number


def require_integer(value: Any, label: str, *, positive: bool = False) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise DashboardError(f"{label} must be an integer")
    if value < 0 or (positive and value <= 0):
        qualifier = "positive" if positive else "non-negative"
        raise DashboardError(f"{label} must be {qualifier}")
    return value


def require_integer_text(value: Any, label: str, *, positive: bool = False) -> int:
    """Accept the CSV-derived integer strings preserved by the exporter."""

    if isinstance(value, bool) or not isinstance(value, (int, str)):
        raise DashboardError(f"{label} must be an integer or decimal integer string")
    try:
        integer = int(value)
    except ValueError as exc:
        raise DashboardError(f"{label} must be a decimal integer string") from exc
    if str(integer) != str(value):
        raise DashboardError(f"{label} must be a canonical decimal integer")
    if integer < 0 or (positive and integer <= 0):
        qualifier = "positive" if positive else "non-negative"
        raise DashboardError(f"{label} must be {qualifier}")
    return integer


def validate_payload(payload: Any) -> dict[str, Any]:
    """Validate and deterministically order the clean schema-version-3 input."""

    root = require_mapping(payload, "headline payload")
    if root.get("schema_version") != 3:
        raise DashboardError("headline schema_version must be exactly 3")
    require_text(root.get("algorithm"), "headline.algorithm")

    series = require_mapping(root.get("series"), "headline.series")
    requested_config = require_text(
        series.get("requested_config"), "headline.series.requested_config"
    )
    if series.get("exponents") != [20, 30]:
        raise DashboardError("headline.series.exponents must be [20, 30]")
    if series.get("word_bits") != 1:
        raise DashboardError("headline.series.word_bits must be 1")
    for key in (
        "measurement_boundary",
        "peak_definition",
        "small_instance_derivation",
        "breakdown_boundary",
    ):
        require_text(series.get(key), f"headline.series.{key}")

    points_value = require_list(root.get("points"), "headline.points")
    points: list[dict[str, Any]] = []
    seen: set[int] = set()
    repetition_counts: set[int] = set()
    for position, point_value in enumerate(points_value):
        point = require_mapping(point_value, f"headline.points[{position}]")
        exponent = require_integer(point.get("i"), f"headline.points[{position}].i")
        if exponent in seen:
            raise DashboardError(f"duplicate headline point for i={exponent}")
        seen.add(exponent)
        if point.get("witness_bits") != 1 << exponent:
            raise DashboardError(f"headline i={exponent}: witness_bits must equal 2^i")
        if point.get("word_bits") != 1:
            raise DashboardError(f"headline i={exponent}: word_bits must be 1")
        if point.get("requested_ligerito") != requested_config:
            raise DashboardError(
                f"headline i={exponent}: requested_ligerito differs from series"
            )

        resolved = require_text(
            point.get("resolved_ligerito"),
            f"headline i={exponent}.resolved_ligerito",
        )
        require_text(
            point.get("resolved_ligerito_label"),
            f"headline i={exponent}.resolved_ligerito_label",
        )

        require_integer_text(
            point.get("threads"), f"headline i={exponent}.threads", positive=True
        )
        repetition_counts.add(
            require_integer(
                point.get("reps"), f"headline i={exponent}.reps", positive=True
            )
        )
        t_value = require_integer(
            point.get("t"), f"headline i={exponent}.t", positive=True
        )
        s_value = require_integer(
            point.get("s"), f"headline i={exponent}.s", positive=True
        )
        if t_value + s_value != exponent:
            raise DashboardError(f"headline i={exponent}: t+s must equal i")
        require_number(
            point.get("prover_ms"), f"headline i={exponent}.prover_ms", positive=True
        )
        require_number(
            point.get("verifier_ms"),
            f"headline i={exponent}.verifier_ms",
            positive=True,
        )
        proof_bytes = require_integer(
            point.get("proof_bytes"),
            f"headline i={exponent}.proof_bytes",
            positive=True,
        )
        proof_kib = require_number(
            point.get("proof_kib"),
            f"headline i={exponent}.proof_kib",
            positive=True,
        )
        if not math.isclose(proof_kib, proof_bytes / 1024.0, rel_tol=1e-9):
            raise DashboardError(
                f"headline i={exponent}: proof_kib disagrees with proof_bytes"
            )
        require_number(
            point.get("prover_peak_heap_mib"),
            f"headline i={exponent}.prover_peak_heap_mib",
            positive=True,
        )
        require_number(
            point.get("commit_ms"),
            f"headline i={exponent}.commit_ms",
            positive=True,
        )
        require_number(
            point.get("commit_peak_heap_mib"),
            f"headline i={exponent}.commit_peak_heap_mib",
            positive=True,
        )

        breakdown = require_mapping(
            point.get("breakdown"), f"headline i={exponent}.breakdown"
        )
        if breakdown.get("i") != exponent:
            raise DashboardError(f"headline i={exponent}: breakdown.i does not match")
        if breakdown.get("requested_ligerito") != requested_config:
            raise DashboardError(
                f"headline i={exponent}: breakdown requested_ligerito differs"
            )
        if breakdown.get("resolved_ligerito") != resolved:
            raise DashboardError(
                f"headline i={exponent}: headline and breakdown configurations differ"
            )
        if breakdown.get("resolved_ligerito_label") != point.get(
            "resolved_ligerito_label"
        ):
            raise DashboardError(
                f"headline i={exponent}: resolved configuration labels differ"
            )
        if breakdown.get("profiled_runs") != 1:
            raise DashboardError(
                f"headline i={exponent}: breakdown.profiled_runs must be 1"
            )
        if breakdown.get("threads") != point.get("threads"):
            raise DashboardError(
                f"headline i={exponent}: headline and breakdown thread counts differ"
            )
        phase_values = {
            key: require_number(
                breakdown.get(key), f"headline i={exponent}.breakdown.{key}"
            )
            for key in PHASE_KEYS
        }
        profiled_total = require_number(
            breakdown.get("profiled_prove_ms"),
            f"headline i={exponent}.breakdown.profiled_prove_ms",
            positive=True,
        )
        tolerance = max(0.05, profiled_total * 1e-5)
        forest_presum = require_number(
            breakdown.get("forest_presum_ms"),
            f"headline i={exponent}.breakdown.forest_presum_ms",
            positive=True,
        )
        ligerito_open = require_number(
            breakdown.get("ligerito_open_ms"),
            f"headline i={exponent}.breakdown.ligerito_open_ms",
            positive=True,
        )
        forest_detail = sum(phase_values[key] for key in PHASE_KEYS[:6])
        opening_detail = sum(phase_values[key] for key in PHASE_KEYS[6:9])
        phase_total = sum(phase_values.values())
        if abs(forest_detail - forest_presum) > tolerance:
            raise DashboardError(
                f"headline i={exponent}: forest detail disagrees with forest_presum_ms"
            )
        if abs(opening_detail - ligerito_open) > tolerance:
            raise DashboardError(
                f"headline i={exponent}: opening detail disagrees with ligerito_open_ms"
            )
        if abs(phase_total - profiled_total) > tolerance:
            raise DashboardError(
                f"headline i={exponent}: detailed phases total {phase_total:.6f} ms, "
                f"profiled prove is {profiled_total:.6f} ms"
            )
        points.append(point)

    if sorted(seen) != EXPECTED_EXPONENTS:
        missing = sorted(set(EXPECTED_EXPONENTS) - seen)
        extra = sorted(seen - set(EXPECTED_EXPONENTS))
        raise DashboardError(
            "headline points must cover i=20..30 exactly; "
            f"missing={missing}, extra={extra}"
        )
    if len(repetition_counts) != 1:
        raise DashboardError(
            "headline points must use one repetition count; "
            f"found={sorted(repetition_counts)}"
        )

    normalized = deepcopy(root)
    normalized["points"] = sorted(points, key=lambda point: int(point["i"]))
    return normalized


def validate_stat(
    value: Any,
    label: str,
    *,
    expected_n: int,
    integer_values: bool = False,
) -> dict[str, Any]:
    stat = require_mapping(value, label)
    med = (
        require_integer(stat.get("med"), f"{label}.med")
        if integer_values
        else require_number(stat.get("med"), f"{label}.med")
    )
    if require_integer(stat.get("n"), f"{label}.n", positive=True) != expected_n:
        raise DashboardError(f"{label}.n must be {expected_n}")
    deciles = require_list(stat.get("dec"), f"{label}.dec")
    if len(deciles) != 9:
        raise DashboardError(f"{label}.dec must contain P10 through P90")
    normalized_deciles: list[float | int] = []
    for index, item in enumerate(deciles, 1):
        normalized_deciles.append(
            require_integer(item, f"{label}.dec[{index - 1}]")
            if integer_values
            else require_number(item, f"{label}.dec[{index - 1}]")
        )
    if any(a > b for a, b in zip(normalized_deciles, normalized_deciles[1:])):
        raise DashboardError(f"{label}.dec must be non-decreasing")
    if not math.isclose(float(med), float(normalized_deciles[4]), rel_tol=1e-12):
        raise DashboardError(f"{label}.med must equal the P50 decile")
    return stat


def validate_event(
    value: Any,
    label: str,
    *,
    measured_n: int,
    root_rep_ms: float,
    is_root: bool = False,
) -> dict[str, Any]:
    event = require_mapping(value, label)
    stable_key = require_text(event.get("stable_key"), f"{label}.stable_key")
    for key in ("label", "op", "name", "short", "group", "kind"):
        require_text(event.get(key), f"{label}.{key}")
    tags = require_list(event.get("tags"), f"{label}.tags")
    if not tags or len(tags) != len(set(tags)):
        raise DashboardError(f"{label}.tags must be a non-empty unique list")
    for index, tag in enumerate(tags):
        require_text(tag, f"{label}.tags[{index}]")
    start = require_number(event.get("start_ms"), f"{label}.start_ms")
    end = require_number(event.get("end_ms"), f"{label}.end_ms")
    rep = require_number(event.get("rep_ms"), f"{label}.rep_ms")
    if end < start:
        raise DashboardError(f"{label}: end_ms precedes start_ms")
    if end > root_rep_ms + max(1e-6, root_rep_ms * 1e-8):
        raise DashboardError(f"{label}: interval escapes the representative root")
    if not math.isclose(end - start, rep, rel_tol=2e-5, abs_tol=2e-5):
        raise DashboardError(f"{label}: rep_ms must equal end_ms - start_ms")
    stat = {
        "med": event.get("med_ms"),
        "n": event.get("n"),
        "dec": event.get("dec_ms"),
    }
    validate_stat(stat, f"{label}.distribution", expected_n=measured_n)
    depth = require_integer(event.get("depth"), f"{label}.depth")
    parent = event.get("parent_key")
    if parent is not None:
        require_text(parent, f"{label}.parent_key")
    occurrence = event.get("occurrence")
    if occurrence is not None:
        require_integer(occurrence, f"{label}.occurrence")
    math_value = event.get("math", [])
    math_list = require_list(math_value, f"{label}.math")
    for index, expression in enumerate(math_list):
        require_text(expression, f"{label}.math[{index}]")
    coordinate = event.get("coordinate")
    if coordinate is not None:
        coordinate_map = require_mapping(coordinate, f"{label}.coordinate")
        for key, item in coordinate_map.items():
            require_text(key, f"{label}.coordinate key")
            if isinstance(item, bool) or not isinstance(item, (str, int, float)):
                raise DashboardError(
                    f"{label}.coordinate.{key} must be a scalar string or number"
                )
    if is_root:
        if stable_key != "root" or depth != 0 or parent is not None or start != 0:
            raise DashboardError(
                f"{label}: root must have stable_key=root, depth=0, no parent, start=0"
            )
    else:
        if stable_key == "root" or depth == 0 or parent is None:
            raise DashboardError(
                f"{label}: non-root intervals need positive depth and parent_key"
            )
    return event


def validate_interval_payload(payload: Any) -> dict[str, Any]:
    """Validate real interval geometry and deterministically order all sizes."""

    root = require_mapping(payload, "interval payload")
    if root.get("schema_version") != 1 or root.get("schema") != INTERVAL_SCHEMA:
        raise DashboardError(
            "interval payload must declare schema_version=1 and "
            f"schema={INTERVAL_SCHEMA!r}"
        )
    require_text(root.get("quantile_method"), "interval.quantile_method")
    geometry = require_text(root.get("geometry"), "interval.geometry")
    geometry_lower = geometry.lower()
    if "unscaled" not in geometry_lower or not (
        "representative" in geometry_lower or "measured trial" in geometry_lower
    ):
        raise DashboardError(
            "interval.geometry must disclose unscaled representative-run intervals"
        )

    validation = require_mapping(root.get("validation"), "interval.validation")
    if validation.get("exponents") != EXPECTED_EXPONENTS:
        raise DashboardError("interval.validation.exponents must be 20..30")
    require_bool(
        validation.get("strict_complete"),
        "interval.validation.strict_complete",
        True,
    )
    if validation.get("trace_schema") != TRACE_SCHEMA:
        raise DashboardError(
            f"interval.validation.trace_schema must be {TRACE_SCHEMA!r}"
        )
    require_bool(
        validation.get("all_sizes_validated"),
        "interval.validation.all_sizes_validated",
        True,
    )

    row_order_value = require_list(root.get("row_order"), "interval.row_order")
    if not row_order_value:
        raise DashboardError("interval.row_order must not be empty")
    row_order: list[dict[str, Any]] = []
    row_tags: set[str] = set()
    for position, row_value in enumerate(row_order_value):
        row = require_mapping(row_value, f"interval.row_order[{position}]")
        tag = require_text(row.get("tag"), f"interval.row_order[{position}].tag")
        require_text(row.get("label"), f"interval.row_order[{position}].label")
        if tag in row_tags:
            raise DashboardError(f"duplicate interval row_order tag {tag!r}")
        row_tags.add(tag)
        row_order.append(row)

    sizes_value = require_list(root.get("sizes"), "interval.sizes")
    sizes: list[dict[str, Any]] = []
    seen_exponents: set[int] = set()
    requested_configs: set[str] = set()
    for position, size_value in enumerate(sizes_value):
        size = require_mapping(size_value, f"interval.sizes[{position}]")
        exponent = require_integer(size.get("i"), f"interval.sizes[{position}].i")
        label = f"interval i={exponent}"
        if exponent in seen_exponents:
            raise DashboardError(f"duplicate interval size i={exponent}")
        seen_exponents.add(exponent)
        t_value = require_integer(size.get("t"), f"{label}.t", positive=True)
        s_value = require_integer(size.get("s"), f"{label}.s", positive=True)
        if t_value + s_value != exponent:
            raise DashboardError(f"{label}: t+s must equal i")
        if size.get("word_bits") != 1:
            raise DashboardError(f"{label}.word_bits must be 1")
        requested_configs.add(
            require_text(size.get("requested_config"), f"{label}.requested_config")
        )
        require_text(size.get("resolved_config"), f"{label}.resolved_config")
        require_integer(size.get("threads"), f"{label}.threads", positive=True)
        warmup_n = require_integer(size.get("warmup_n"), f"{label}.warmup_n")
        measured_n = require_integer(
            size.get("measured_n"), f"{label}.measured_n", positive=True
        )
        if warmup_n != 1 or measured_n != 21:
            raise DashboardError(f"{label}: expected 1 warmup and 21 measured trials")
        representative = require_integer(
            size.get("representative_trial"), f"{label}.representative_trial"
        )
        if representative >= measured_n:
            raise DashboardError(f"{label}.representative_trial is out of range")
        require_text(
            size.get("representative_run_id"), f"{label}.representative_run_id"
        )
        root_rep_ms = require_number(
            size.get("root_rep_ms"), f"{label}.root_rep_ms", positive=True
        )
        root_median_ms = require_number(
            size.get("root_median_ms"), f"{label}.root_median_ms", positive=True
        )
        scale = require_number(
            size.get("geometry_scale"), f"{label}.geometry_scale", positive=True
        )
        if scale != 1.0:
            raise DashboardError(f"{label}.geometry_scale must be exactly 1.0")

        metrics = require_mapping(size.get("metrics"), f"{label}.metrics")
        for key in METRIC_KEYS:
            validate_stat(
                metrics.get(key), f"{label}.metrics.{key}", expected_n=measured_n
            )
        if not math.isclose(
            float(metrics["trial"]["med"]), root_median_ms, rel_tol=1e-12
        ):
            raise DashboardError(f"{label}: root_median_ms disagrees with trial P50")

        root_event = validate_event(
            size.get("root"),
            f"{label}.root",
            measured_n=measured_n,
            root_rep_ms=root_rep_ms,
            is_root=True,
        )
        if not math.isclose(float(root_event["end_ms"]), root_rep_ms, rel_tol=1e-12):
            raise DashboardError(f"{label}: root end_ms disagrees with root_rep_ms")

        primary_value = require_list(size.get("primary"), f"{label}.primary")
        if not primary_value:
            raise DashboardError(f"{label}.primary must not be empty")
        primary: list[dict[str, Any]] = []
        canonical: dict[str, dict[str, Any]] = {}
        for event_position, event_value in enumerate(primary_value):
            event = validate_event(
                event_value,
                f"{label}.primary[{event_position}]",
                measured_n=measured_n,
                root_rep_ms=root_rep_ms,
            )
            stable_key = event["stable_key"]
            if stable_key in canonical:
                raise DashboardError(f"{label}: duplicate primary event {stable_key!r}")
            canonical[stable_key] = event
            primary.append(event)
        if primary != sorted(
            primary,
            key=lambda event: (
                event["start_ms"],
                event["end_ms"],
                event["stable_key"],
            ),
        ):
            raise DashboardError(f"{label}.primary must be ordered by real geometry")

        rows_value = require_mapping(size.get("rows"), f"{label}.rows")
        unknown_rows = sorted(set(rows_value) - row_tags)
        if unknown_rows:
            raise DashboardError(f"{label}.rows contains unknown tags {unknown_rows}")
        rows: dict[str, list[dict[str, Any]]] = {}
        for tag in (row["tag"] for row in row_order):
            if tag not in rows_value:
                continue
            row_events_value = require_list(rows_value[tag], f"{label}.rows.{tag}")
            if not row_events_value:
                raise DashboardError(f"{label}.rows.{tag} must not be empty")
            row_events: list[dict[str, Any]] = []
            row_seen: set[str] = set()
            for event_position, event_value in enumerate(row_events_value):
                event = validate_event(
                    event_value,
                    f"{label}.rows.{tag}[{event_position}]",
                    measured_n=measured_n,
                    root_rep_ms=root_rep_ms,
                )
                if tag not in event["tags"]:
                    raise DashboardError(
                        f"{label}.rows.{tag}: event {event['stable_key']!r} lacks its row tag"
                    )
                stable_key = event["stable_key"]
                if stable_key in row_seen:
                    raise DashboardError(
                        f"{label}.rows.{tag}: duplicate event {stable_key!r}"
                    )
                row_seen.add(stable_key)
                previous = canonical.get(stable_key)
                if previous is not None and previous != event:
                    raise DashboardError(
                        f"{label}: event {stable_key!r} differs between semantic views"
                    )
                canonical.setdefault(stable_key, event)
                row_events.append(event)
            if row_events != sorted(
                row_events,
                key=lambda event: (
                    event["start_ms"],
                    event["end_ms"],
                    event["stable_key"],
                ),
            ):
                raise DashboardError(f"{label}.rows.{tag} must be ordered by geometry")
            rows[tag] = row_events

        proof = require_mapping(size.get("proof"), f"{label}.proof")
        validate_stat(
            proof.get("total"),
            f"{label}.proof.total",
            expected_n=measured_n,
            integer_values=True,
        )
        artifacts = require_mapping(proof.get("artifacts"), f"{label}.proof.artifacts")
        if not artifacts:
            raise DashboardError(f"{label}.proof.artifacts must not be empty")
        for key, value in artifacts.items():
            require_text(key, f"{label}.proof.artifacts key")
            validate_stat(
                value,
                f"{label}.proof.artifacts.{key}",
                expected_n=measured_n,
                integer_values=True,
            )
        if "fnv" in proof:
            fnvs = require_list(proof["fnv"], f"{label}.proof.fnv")
            if len(fnvs) != measured_n:
                raise DashboardError(f"{label}.proof.fnv must contain one hash per trial")
            for index, fnv in enumerate(fnvs):
                text = require_text(fnv, f"{label}.proof.fnv[{index}]")
                if len(text) != 16 or any(char not in "0123456789abcdef" for char in text):
                    raise DashboardError(
                        f"{label}.proof.fnv[{index}] must be 16 lowercase hex digits"
                    )

        size_validation = require_mapping(size.get("validation"), f"{label}.validation")
        if size_validation.get("sample_indices") != list(range(21)):
            raise DashboardError(f"{label}.validation.sample_indices must be 0..20")
        if size_validation.get("warmup_indices") != [0]:
            raise DashboardError(f"{label}.validation.warmup_indices must be [0]")
        stable_event_count = require_integer(
            size_validation.get("stable_event_count"),
            f"{label}.validation.stable_event_count",
            positive=True,
        )
        if stable_event_count < len(canonical):
            raise DashboardError(
                f"{label}.validation.stable_event_count is smaller than rendered events"
            )
        for key in (
            "real_representative_geometry",
            "all_events_present_every_trial",
            "proof_artifacts_reconcile_every_trial",
        ):
            require_bool(
                size_validation.get(key), f"{label}.validation.{key}", True
            )
        normalized_size = deepcopy(size)
        normalized_size["primary"] = primary
        normalized_size["rows"] = rows
        sizes.append(normalized_size)

    if sorted(seen_exponents) != EXPECTED_EXPONENTS:
        missing = sorted(set(EXPECTED_EXPONENTS) - seen_exponents)
        extra = sorted(seen_exponents - set(EXPECTED_EXPONENTS))
        raise DashboardError(
            "interval sizes must cover i=20..30 exactly; "
            f"missing={missing}, extra={extra}"
        )
    if len(requested_configs) != 1:
        raise DashboardError(
            f"interval sizes use inconsistent requested configs: {sorted(requested_configs)}"
        )
    normalized = deepcopy(root)
    normalized["sizes"] = sorted(sizes, key=lambda size: int(size["i"]))
    normalized["row_order"] = row_order
    return normalized


def validate_cross_inputs(
    headline: dict[str, Any], intervals: dict[str, Any]
) -> None:
    """Reject a dashboard whose clean and profiled series are not the same sweep."""

    for point, size in zip(headline["points"], intervals["sizes"], strict=True):
        exponent = point["i"]
        if size["i"] != exponent:
            raise DashboardError("headline and interval exponents are not aligned")
        for key in ("t", "s", "word_bits"):
            if point[key] != size[key]:
                raise DashboardError(
                    f"i={exponent}: headline and interval {key} values differ"
                )
        if point["requested_ligerito"] != size["requested_config"]:
            raise DashboardError(
                f"i={exponent}: headline and interval requested configs differ"
            )
        if point["resolved_ligerito"] != size["resolved_config"]:
            raise DashboardError(
                f"i={exponent}: headline and interval resolved configs differ"
            )
        if require_integer_text(point["threads"], "threads") != size["threads"]:
            raise DashboardError(
                f"i={exponent}: headline and interval thread counts differ"
            )
        if point["reps"] != size["measured_n"]:
            raise DashboardError(
                f"i={exponent}: headline reps and interval measured trials differ"
            )
        interval_proof = size["proof"]["total"]["med"]
        if point["proof_bytes"] != interval_proof:
            raise DashboardError(
                f"i={exponent}: clean and interval P50 proof bytes differ "
                f"({point['proof_bytes']} != {interval_proof})"
            )


def json_for_script(payload: dict[str, Any]) -> str:
    """Serialize JSON without permitting an embedded closing script tag."""

    serialized = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return (
        serialized.replace("&", r"\u0026")
        .replace("<", r"\u003c")
        .replace(">", r"\u003e")
        .replace("\u2028", r"\u2028")
        .replace("\u2029", r"\u2029")
    )


HTML_TEMPLATE = r'''<!doctype html>
__GENERATED_MARKER__
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>F2Z PCS · requested __PROFILE_HTML__ interval benchmark</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #fbfbfa;
      --panel: #ffffff;
      --panel-2: #f4f4f2;
      --fg: #191b1f;
      --muted: #666c76;
      --faint: #8c929c;
      --border: #dedfdf;
      --grid: #e8e9e8;
      --accent: #2368df;
      --accent-soft: #eaf1ff;
      --focus: #005fcc;
      --c-commit: #c2410c;
      --c-prove: #b42318;
      --c-verify: #0f766e;
      --c-pcs: #1d4ed8;
      --c-open: #2563eb;
      --c-sum: #7e22ce;
      --c-fri: #be185d;
      --c-prep: #0f766e;
      --c-serialize: #6b7280;
      --c-other: #525862;
      --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
      --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, system-ui, sans-serif;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        color-scheme: dark;
        --bg: #151619;
        --panel: #1d1f23;
        --panel-2: #25272c;
        --fg: #eceef2;
        --muted: #a5aab4;
        --faint: #7f858f;
        --border: #34373d;
        --grid: #2b2e33;
        --accent: #79a5ff;
        --accent-soft: #203253;
        --focus: #8ab2ff;
        --c-commit: #fb8b3c;
        --c-prove: #f87171;
        --c-verify: #2dd4bf;
        --c-pcs: #60a5fa;
        --c-open: #60a5fa;
        --c-sum: #c084fc;
        --c-fri: #f472b6;
        --c-prep: #2dd4bf;
        --c-serialize: #a4aab4;
        --c-other: #8b929d;
      }
    }

    * { box-sizing: border-box; }
    html, body { margin: 0; background: var(--bg); color: var(--fg); }
    html { scroll-behavior: smooth; }
    body {
      font-family: var(--sans);
      font-size: 14px;
      line-height: 1.5;
      -webkit-font-smoothing: antialiased;
    }
    button, select { font: inherit; }
    button:focus-visible, select:focus-visible, a:focus-visible {
      outline: 3px solid var(--focus);
      outline-offset: 2px;
    }
    .skip-link {
      position: absolute;
      left: 18px;
      top: -80px;
      z-index: 100;
      padding: 8px 12px;
      border: 1px solid var(--border);
      border-radius: 7px;
      background: var(--panel);
      color: var(--fg);
    }
    .skip-link:focus { top: 12px; }
    .wrap { max-width: 1240px; margin: 0 auto; padding: 32px 24px 80px; }
    header { margin-bottom: 20px; }
    h1 { margin: 0 0 6px; font-size: 24px; font-weight: 650; letter-spacing: -.02em; }
    h2 { margin: 0 0 3px; font-size: 15px; font-weight: 650; }
    p { margin-top: 0; }
    .sub { max-width: 86ch; margin-bottom: 0; color: var(--muted); font-size: 13.5px; }
    code { font-family: var(--mono); font-size: .92em; }
    .badges { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 16px; }
    .badge {
      display: inline-flex;
      align-items: baseline;
      gap: 6px;
      padding: 4px 11px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: var(--panel);
      font-size: 12px;
    }
    .badge span { color: var(--muted); }
    .badge b { font-weight: 650; }
    .tabs { display: flex; flex-wrap: wrap; gap: 6px; margin: 22px 0 18px; }
    .tab {
      appearance: none;
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 7px 14px;
      background: var(--panel);
      color: var(--muted);
      cursor: pointer;
      transition: color .12s, background .12s, border-color .12s;
    }
    .tab:hover { color: var(--fg); }
    .tab[aria-selected="true"] {
      border-color: var(--accent);
      background: var(--accent);
      color: #fff;
      font-weight: 600;
    }
    .tiles {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 9px;
      margin-bottom: 22px;
    }
    .tile {
      position: relative;
      overflow: hidden;
      min-width: 0;
      padding: 11px 13px;
      border: 1px solid var(--border);
      border-radius: 10px;
      background: var(--panel);
    }
    .tile::before {
      position: absolute;
      inset: 0 auto 0 0;
      width: 3px;
      background: var(--tc, var(--c-other));
      content: "";
    }
    .tile .k { margin-bottom: 3px; color: var(--muted); font-size: 11px; letter-spacing: .055em; text-transform: uppercase; }
    .tile .v { font: 650 19px var(--mono); letter-spacing: -.02em; }
    .tile .v small { margin-left: 2px; color: var(--muted); font-size: 11.5px; font-weight: 400; }
    .tile .d { margin-top: 3px; color: var(--faint); font: 10.5px var(--mono); }
    main { min-width: 0; }
    .card {
      margin-bottom: 18px;
      padding: 18px 18px 12px;
      border: 1px solid var(--border);
      border-radius: 12px;
      background: var(--panel);
    }
    .hint { margin: 0 0 14px; color: var(--muted); font-size: 12px; }
    .timeline-wrap { width: 100%; overflow-x: auto; }
    #timeline { display: block; width: 100%; min-width: 520px; overflow: visible; }
    .row-label { fill: var(--muted); font-size: 11.5px; }
    .row-label.head { fill: var(--fg); font-weight: 650; }
    .row-rule { stroke: var(--grid); stroke-width: 1; }
    .row-band { fill: var(--panel-2); opacity: .6; }
    .axis { fill: var(--faint); font: 10.5px var(--mono); }
    .axis-line { stroke: var(--grid); stroke-width: 1; stroke-dasharray: 2 3; }
    .bar { cursor: pointer; rx: 2.5; }
    .bar:hover { filter: brightness(1.14); }
    .bar.sel { stroke: var(--fg); stroke-width: 1.5; }
    .bar-label { pointer-events: none; fill: #fff; font-size: 10px; font-weight: 600; }
    .inspector { padding-bottom: 18px; }
    .inspect-grid { display: grid; grid-template-columns: minmax(240px, 360px) 1fr; gap: 18px; align-items: start; }
    .inspect-grid label { display: block; color: var(--muted); font-size: 12px; }
    .inspect-grid select {
      display: block;
      width: 100%;
      margin-top: 6px;
      padding: 8px 10px;
      border: 1px solid var(--border);
      border-radius: 7px;
      background: var(--panel-2);
      color: var(--fg);
    }
    .inspect-title { margin-bottom: 2px; font-weight: 650; }
    .inspect-op { color: var(--muted); font: 11px var(--mono); word-break: break-all; }
    .inspect-metrics { display: flex; flex-wrap: wrap; gap: 7px 16px; margin: 8px 0; color: var(--muted); font-size: 12px; }
    .inspect-metrics b { color: var(--fg); font: 500 12px var(--mono); }
    .tags { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }
    .tag { padding: 1px 6px; border: 1px solid var(--border); border-radius: 4px; background: var(--panel-2); color: var(--muted); font-size: 10px; }
    .math-list { margin-top: 9px; padding-top: 8px; border-top: 1px solid var(--border); color: var(--muted); font: 12px var(--mono); overflow-wrap: anywhere; }
    .math-list div + div { margin-top: 4px; }
    .artifact-list { margin-top: 8px; padding-top: 7px; border-top: 1px solid var(--border); color: var(--muted); font-size: 12px; }
    .artifact-list b { color: var(--fg); font-family: var(--mono); font-weight: 500; }
    .table-responsive { width: 100%; overflow-x: auto; }
    table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    th, td { padding: 7px 9px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: top; }
    th { color: var(--muted); font-size: 10.5px; font-weight: 650; letter-spacing: .045em; text-transform: uppercase; }
    td.num, th.num { text-align: right; font-family: var(--mono); white-space: nowrap; }
    tr[data-selected="true"] { background: var(--accent-soft); }
    .step { display: flex; align-items: baseline; gap: 7px; min-width: 180px; }
    .step-name { padding-left: calc(var(--depth, 0) * 13px); }
    .dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 2px; background: var(--dot); }
    .metric-link { appearance: none; border: 0; padding: 0; background: transparent; color: var(--accent); font: inherit; font-weight: 650; text-decoration: underline; text-underline-offset: 2px; cursor: pointer; }
    .note { margin: 14px 0; padding: 10px 13px; border-left: 3px solid var(--accent); border-radius: 0 7px 7px 0; background: var(--panel-2); color: var(--muted); font-size: 12.5px; }
    .note b { color: var(--fg); }
    .headline-card { position: relative; padding-bottom: 16px; }
    .exact-series { margin-bottom: 24px; }
    .headline-legend { display: flex; flex-wrap: wrap; gap: 8px 18px; margin: -2px 0 8px; color: var(--muted); font-size: 11.5px; }
    .legend-item { display: inline-flex; align-items: center; gap: 6px; }
    .legend-line { width: 20px; height: 3px; border-radius: 2px; background: var(--legend); }
    #headline-chart { display: block; width: 100%; min-height: 430px; overflow: visible; touch-action: pan-y; }
    .chart-frame { fill: none; stroke: var(--border); stroke-width: 1; }
    .chart-grid { stroke: var(--grid); stroke-width: 1; }
    .chart-axis { fill: var(--muted); font: 10.5px var(--mono); }
    .chart-title { fill: var(--fg); font-size: 11.5px; font-weight: 650; }
    .chart-subtitle { fill: var(--faint); font-size: 10px; }
    .chart-line { fill: none; stroke-width: 2.2; stroke-linejoin: round; stroke-linecap: round; }
    .chart-point { stroke: var(--panel); stroke-width: 1.5; }
    .selected-band { fill: var(--accent-soft); }
    .hover-guide { stroke: var(--accent); stroke-width: 1; stroke-dasharray: 3 3; pointer-events: none; }
    .chart-hit { fill: transparent; cursor: crosshair; }
    .graph-tip {
      position: absolute;
      z-index: 20;
      display: none;
      min-width: 190px;
      padding: 9px 11px;
      border: 1px solid var(--border);
      border-radius: 9px;
      background: var(--panel);
      box-shadow: 0 8px 26px rgb(0 0 0 / 17%);
      pointer-events: none;
      font-size: 11.5px;
    }
    .graph-tip.on { display: block; }
    .graph-tip .tip-head { margin-bottom: 5px; font-weight: 650; }
    .graph-tip .tip-row { display: flex; justify-content: space-between; gap: 16px; color: var(--muted); }
    .graph-tip .tip-row b { color: var(--fg); font-family: var(--mono); font-weight: 500; }
    #interval-tip {
      position: fixed;
      z-index: 50;
      display: none;
      max-width: 390px;
      padding: 11px 13px;
      border: 1px solid var(--border);
      border-radius: 10px;
      background: var(--panel);
      box-shadow: 0 8px 26px rgb(0 0 0 / 17%);
      pointer-events: none;
      font-size: 12.5px;
    }
    #interval-tip.on { display: block; }
    #interval-tip .tip-name { margin-bottom: 2px; font-weight: 650; line-height: 1.35; }
    #interval-tip .tip-op { margin-bottom: 8px; color: var(--muted); font: 11px var(--mono); word-break: break-all; }
    #interval-tip .tip-big { font: 650 16px var(--mono); }
    #interval-tip .tip-row { display: flex; justify-content: space-between; gap: 14px; margin-top: 2px; color: var(--muted); font-size: 11.5px; }
    #interval-tip .tip-row b { color: var(--fg); font-family: var(--mono); font-weight: 500; }
    #interval-tip .decile-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 3px 10px; margin-top: 7px; }
    #interval-tip .decile-grid span { display: flex; justify-content: space-between; gap: 5px; color: var(--muted); font-size: 10.5px; }
    #interval-tip .decile-grid b { color: var(--fg); font-family: var(--mono); font-weight: 500; }
    .spark { margin-top: 8px; }
    .spark-labels { display: flex; justify-content: space-between; color: var(--faint); font: 10px var(--mono); }
    footer { margin-top: 26px; color: var(--faint); font-size: 11.5px; line-height: 1.65; }
    footer b { color: var(--muted); font-weight: 650; }

    @media (max-width: 680px) {
      .wrap { padding: 24px 14px 60px; }
      .inspect-grid { grid-template-columns: 1fr; }
      .card { padding-inline: 12px; }
      .tab { flex: 1 0 calc(25% - 6px); padding-inline: 8px; }
      .tiles { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .tile .v { font-size: 16px; }
      #headline-chart { min-height: 460px; }
    }
  </style>
</head>
<body>
  <a class="skip-link" href="#interval-explorer">Skip to interval explorer</a>
  <div class="wrap">
    <header>
      <h1>F2Z PCS · requested <code>__PROFILE_HTML__</code> intervals</h1>
      <p class="sub">Real wall-clock spans for commit, PCS proving, serialization, and verification across witness sizes 2<sup>20</sup>–2<sup>30</sup>. The timeline preserves nesting and overlap from one measured representative run; P10–P90 comes from 21 fresh measured trials.</p>
      <div class="badges" id="badges" aria-label="Selected benchmark configuration"></div>
    </header>

    <nav class="tabs" id="tabs" role="tablist" aria-label="Witness exponent"></nav>
    <div class="tiles" id="tiles" aria-label="Selected-size interval summaries"></div>

    <main id="interval-explorer">
      <section class="card" aria-labelledby="timeline-title">
        <h2 id="timeline-title">Interval timeline</h2>
        <p class="hint">The top row is the actual phase sequence. Rows below are overlapping semantic views of that same run: one span can be proving, PCS, opening proof, and FRI at once. Bars remain at their observed wall-clock positions. Hover or tap a bar for its median, all sample deciles, and representative duration; click to pin it.</p>
        <div class="timeline-wrap"><svg id="timeline" role="img" aria-labelledby="timeline-svg-title timeline-svg-desc"><title id="timeline-svg-title">Representative benchmark interval timeline</title><desc id="timeline-svg-desc">Wall-clock interval bars for the selected witness exponent.</desc></svg></div>
      </section>

      <section class="card inspector" aria-labelledby="inspector-title">
        <h2 id="inspector-title">Pinned interval</h2>
        <p class="hint">The selected procedure stays pinned while you switch witness sizes, making its runtime distribution and recurrence metadata directly comparable.</p>
        <div class="inspect-grid">
          <label for="interval-select">Inspect interval
            <select id="interval-select"></select>
          </label>
          <div id="interval-detail" aria-live="polite"></div>
        </div>
      </section>

      <div class="note"><b>Intervals are observed, not reconstructed.</b> Bar geometry is the unscaled start/end position from the measured trial nearest the Type-7 median trial time. Tooltip and table values are independent per-interval medians, so a bar’s width can differ from its P50. Semantic rows are overlapping views, not additive parts.</div>

      <section class="card headline-card" id="headline-scaling" aria-labelledby="headline-title">
        <h2 id="headline-title">Clean headline scaling</h2>
        <p class="hint">A separate coordinated graph for the four headline measures. Time and heap use logarithmic vertical scales; proof size is linear. Move across any lane to compare one exponent, or click it to select the matching interval trace above.</p>
        <div class="headline-legend" aria-label="Headline series legend">
          <span class="legend-item"><span class="legend-line" style="--legend:var(--c-prove)"></span>PCS prove P50</span>
          <span class="legend-item"><span class="legend-line" style="--legend:var(--c-verify)"></span>Verifier P50</span>
          <span class="legend-item"><span class="legend-line" style="--legend:var(--c-pcs)"></span>Exact proof size</span>
          <span class="legend-item"><span class="legend-line" style="--legend:var(--c-sum)"></span>Prover peak tracked heap</span>
        </div>
        <svg id="headline-chart" role="img" aria-labelledby="headline-svg-title headline-svg-desc"><title id="headline-svg-title">Clean headline metrics across witness exponents</title><desc id="headline-svg-desc">Three aligned lanes show prove and verifier time, proof size, and prover peak tracked heap for exponents 20 through 30.</desc></svg>
        <div class="graph-tip" id="graph-tip" role="tooltip"></div>
      </section>

      <div class="note"><b>Memory is a scalar high-water mark, not an interval.</b> Peak tracked heap is the maximum outstanding Rust allocation bytes during one separate prove, with the live commitment hint included. It is not RSS and cannot be placed honestly on the wall-clock timeline.</div>

      <section class="exact-series" aria-labelledby="exact-title">
        <h2 id="exact-title">Exact headline series</h2>
        <p class="hint">Clean proof bytes are exact; timing and memory columns retain the report units and measurement boundaries.</p>
        <div class="table-responsive">
          <table id="headline-table">
            <thead><tr><th>Witness</th><th>Resolved Ligerito</th><th class="num">PCS prove P50 (ms)</th><th class="num">Verifier P50 (ms)</th><th class="num">Proof (bytes)</th><th class="num">Proof (KiB)</th><th class="num">Prover peak heap (MiB)</th><th class="num">Commit (ms)</th></tr></thead>
            <tbody></tbody>
          </table>
        </div>
      </section>

      <section class="card" aria-labelledby="phase-title">
        <h2 id="phase-title">Phase breakdown</h2>
        <p class="hint">P50 and P10–P90 are computed per stable interval across 21 trials. Nested rows are contained by their primary phase; semantic tags still overlap and must not be summed.</p>
        <div class="table-responsive">
          <table id="phase-table">
            <thead><tr><th>Step</th><th class="num">P50</th><th class="num">P10–P90</th><th class="num">% of trial</th><th>Tags</th></tr></thead>
            <tbody></tbody>
          </table>
        </div>
      </section>
    </main>

    <footer id="footer"></footer>
  </div>
  <div id="interval-tip" role="tooltip"></div>
  <script type="application/json" id="headline-data">__HEADLINE_DATA__</script>
  <script type="application/json" id="interval-data">__INTERVAL_DATA__</script>
  <script>
  (() => {
    "use strict";
    const HEADLINE = JSON.parse(document.getElementById("headline-data").textContent);
    const INTERVALS = JSON.parse(document.getElementById("interval-data").textContent);
    const pointsByExponent = new Map(HEADLINE.points.map(point => [point.i, point]));
    const sizesByExponent = new Map(INTERVALS.sizes.map(size => [size.i, size]));
    const tabs = document.getElementById("tabs");
    const intervalTip = document.getElementById("interval-tip");
    const graphTip = document.getElementById("graph-tip");
    let selectedExponent = 30;
    let selectedKey = "";
    let selectedIdentity = "";
    let pinnedTooltip = false;
    let hoverGraphExponent = null;
    let resizeFrame = 0;

    const escapeHtml = value => String(value)
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#39;");
    const fmtMs = value => value >= 100 ? value.toFixed(1) : value >= 10 ? value.toFixed(2) : value >= 1 ? value.toFixed(3) : (value * 1000).toFixed(1);
    const unitMs = value => value >= 1 ? "ms" : "µs";
    const fmtDuration = value => `${fmtMs(value)} ${unitMs(value)}`;
    const fmtBytes = bytes => {
      const units = ["B", "KiB", "MiB", "GiB"];
      let value = Number(bytes), index = 0;
      while (value >= 1024 && index < units.length - 1) { value /= 1024; index += 1; }
      const digits = value >= 100 ? 0 : value >= 10 ? 1 : 2;
      return `${value.toFixed(digits)} ${units[index]}`;
    };
    const fmtPct = (part, whole) => `${(100 * part / whole).toFixed(1)}%`;
    const eventIdentity = item => [item.op, item.name, item.depth, item.occurrence ?? ""].join("|");
    const svgNS = "http://www.w3.org/2000/svg";
    const svgNode = (name, attributes = {}, text = null) => {
      const node = document.createElementNS(svgNS, name);
      Object.entries(attributes).forEach(([key, value]) => node.setAttribute(key, value));
      if (text !== null) node.textContent = text;
      return node;
    };
    const colorFor = item => {
      if (item.tags.includes("verification")) return "var(--c-verify)";
      if (item.tags.includes("serialization")) return "var(--c-serialize)";
      if (item.tags.includes("fri")) return "var(--c-fri)";
      if (item.tags.includes("sumcheck")) return "var(--c-sum)";
      if (item.tags.includes("commit")) return "var(--c-commit)";
      if (item.tags.includes("opening-proof") || item.tags.includes("pcs")) return "var(--c-open)";
      if (item.tags.includes("proving")) return "var(--c-prove)";
      if (item.tags.includes("preparation")) return "var(--c-prep)";
      return "var(--c-other)";
    };

    function allIntervals(size) {
      const found = new Map();
      [...size.primary, ...Object.values(size.rows).flat()].forEach(item => {
        if (!found.has(item.stable_key)) found.set(item.stable_key, item);
      });
      return [...found.values()].sort((a, b) => a.start_ms - b.start_ms || a.end_ms - b.end_ms || a.name.localeCompare(b.name));
    }

    function resolveSelection(size) {
      const items = allIntervals(size);
      let selected = items.find(item => item.stable_key === selectedKey);
      if (!selected && selectedIdentity) selected = items.find(item => eventIdentity(item) === selectedIdentity);
      if (!selected) selected = items.find(item => /^bench[.:]prove$/.test(item.op)) || size.primary[0] || items[0];
      selectedKey = selected.stable_key;
      selectedIdentity = eventIdentity(selected);
      return selected;
    }

    function renderTabs() {
      tabs.innerHTML = "";
      INTERVALS.sizes.forEach(size => {
        const button = document.createElement("button");
        button.type = "button";
        button.className = "tab";
        button.setAttribute("role", "tab");
        button.setAttribute("aria-selected", String(size.i === selectedExponent));
        button.setAttribute("aria-controls", "interval-explorer");
        button.textContent = `2^${size.i}`;
        button.addEventListener("click", () => selectExponent(size.i));
        tabs.appendChild(button);
      });
    }

    function renderBadges(size) {
      const values = [
        ["Requested", size.requested_config],
        ["Resolved", size.resolved_config],
        ["Witness", `2^${size.i} bits`],
        ["Shape", `t=${size.t}, s=${size.s}`],
        ["Threads", size.threads],
        ["Samples", `${size.warmup_n} warmup + ${size.measured_n} measured`],
        ["Representative", `sample ${size.representative_trial}`],
      ];
      document.getElementById("badges").innerHTML = values.map(([key, value]) => `<span class="badge"><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></span>`).join("");
    }

    function renderTiles(size) {
      const definitions = [
        ["Trace trial P50", "trial", "var(--c-other)"],
        ["Trace commit P50", "commit", "var(--c-commit)"],
        ["Trace PCS prove P50", "prove", "var(--c-prove)"],
        ["Trace serialize P50", "serialize", "var(--c-serialize)"],
        ["Trace verifier P50", "verify", "var(--c-verify)"],
      ];
      const rootMedian = size.metrics.trial.med;
      const tiles = definitions.map(([label, key, color]) => {
        const stat = size.metrics[key];
        const context = key === "trial" ? `representative ${fmtDuration(size.root_rep_ms)}` : `${fmtPct(stat.med, rootMedian)} of trial · n=${stat.n}`;
        return `<div class="tile" style="--tc:${color}"><div class="k">${escapeHtml(label)}</div><div class="v">${escapeHtml(fmtMs(stat.med))}<small>${escapeHtml(unitMs(stat.med))}</small></div><div class="d">${escapeHtml(context)}</div></div>`;
      });
      tiles.push(`<div class="tile" style="--tc:var(--c-pcs)"><div class="k">Serialized proof P50</div><div class="v">${escapeHtml(fmtBytes(size.proof.total.med))}</div><div class="d">P10 ${escapeHtml(fmtBytes(size.proof.total.dec[0]))} · P90 ${escapeHtml(fmtBytes(size.proof.total.dec[8]))}</div></div>`);
      document.getElementById("tiles").innerHTML = tiles.join("");
    }

    function drawTimeline(size) {
      const svg = document.getElementById("timeline");
      svg.querySelectorAll(":scope > :not(title):not(desc)").forEach(node => node.remove());
      const left = Math.min(132, Math.max(105, svg.clientWidth * .19));
      const right = 18, top = 25, rowHeight = 30, gap = 5, headHeight = 38;
      const width = Math.max(520, svg.clientWidth || 900);
      const rows = [{ tag: "__phase__", label: "Phase sequence", items: size.primary, head: true }];
      INTERVALS.row_order.forEach(row => {
        if (size.rows[row.tag]?.length) rows.push({ ...row, items: size.rows[row.tag], head: false });
      });
      const height = top + headHeight + rows.length * (rowHeight + gap) + 8;
      svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
      svg.setAttribute("height", String(height));
      const plotWidth = width - left - right;
      const x = milliseconds => left + milliseconds / size.root_rep_ms * plotWidth;
      const tickCount = width < 650 ? 4 : 6;
      const axisUnit = unitMs(size.root_rep_ms);
      const axisScale = axisUnit === "ms" ? 1 : 1000;
      for (let index = 0; index <= tickCount; index += 1) {
        const milliseconds = size.root_rep_ms * index / tickCount;
        const px = x(milliseconds);
        svg.appendChild(svgNode("line", { x1: px, y1: top + 18, x2: px, y2: height - 6, class: "axis-line" }));
        svg.appendChild(svgNode("text", {
          x: px,
          y: top + 10,
          class: "axis",
          "text-anchor": index === 0 ? "start" : index === tickCount ? "end" : "middle",
        }, `${fmtMs(milliseconds * axisScale)} ${axisUnit}`));
      }
      rows.forEach((row, rowIndex) => {
        const y = top + headHeight + rowIndex * (rowHeight + gap);
        if (rowIndex % 2 === 1) svg.appendChild(svgNode("rect", { x: left, y: y - 2, width: plotWidth, height: rowHeight + 4, class: "row-band" }));
        svg.appendChild(svgNode("text", { x: left - 10, y: y + rowHeight / 2 + 4, class: `row-label${row.head ? " head" : ""}`, "text-anchor": "end" }, row.label));
        svg.appendChild(svgNode("line", { x1: left, y1: y + rowHeight + gap / 2 - 1, x2: width - right, y2: y + rowHeight + gap / 2 - 1, class: "row-rule" }));
        row.items.forEach(item => {
          const x0 = x(item.start_ms);
          const x1 = Math.max(x(item.end_ms), x0 + 1.6);
          const bar = svgNode("rect", {
            x: x0,
            y: y + 3,
            width: x1 - x0,
            height: rowHeight - 6,
            fill: colorFor(item),
            class: `bar${item.stable_key === selectedKey ? " sel" : ""}`,
            "aria-label": `${item.name}, median ${fmtDuration(item.med_ms)}`,
          });
          bar.addEventListener("pointerenter", event => showIntervalTip(event, item, size, false));
          bar.addEventListener("pointermove", event => moveIntervalTip(event));
          bar.addEventListener("pointerleave", () => hideIntervalTip(false));
          bar.addEventListener("click", event => {
            event.stopPropagation();
            selectedKey = item.stable_key;
            selectedIdentity = eventIdentity(item);
            pinnedTooltip = true;
            renderInspector(size);
            drawTimeline(size);
            showIntervalTip(event, item, size, true);
          });
          svg.appendChild(bar);
          if (x1 - x0 > 46 && item.short) {
            const maxCharacters = Math.floor((x1 - x0 - 8) / 5.7);
            const text = item.short.length > maxCharacters ? `${item.short.slice(0, Math.max(1, maxCharacters - 1))}…` : item.short;
            svg.appendChild(svgNode("text", { x: x0 + 5, y: y + rowHeight / 2 + 4, class: "bar-label" }, text));
          }
        });
      });
    }

    function sparkline(deciles) {
      const width = 210, low = deciles[0], high = deciles[8], range = Math.max(high - low, 1e-12);
      const position = value => 2 + (value - low) / range * (width - 4);
      return `<svg width="${width}" height="16" aria-hidden="true"><line x1="2" y1="8" x2="${width - 2}" y2="8" stroke="var(--border)"/><rect x="${position(deciles[2])}" y="4" width="${Math.max(2, position(deciles[6]) - position(deciles[2]))}" height="8" fill="var(--accent)" opacity=".3" rx="2"/>${deciles.map((value, index) => `<line x1="${position(value)}" y1="${index === 4 ? 2 : 5}" x2="${position(value)}" y2="${index === 4 ? 14 : 11}" stroke="${index === 4 ? "var(--accent)" : "var(--faint)"}" stroke-width="${index === 4 ? 2 : 1}"/>`).join("")}</svg>`;
    }

    function showIntervalTip(event, item, size, pin) {
      if (pinnedTooltip && !pin) return;
      pinnedTooltip = pin || pinnedTooltip;
      const recurrence = [];
      if (item.occurrence !== null) recurrence.push(["occurrence", item.occurrence]);
      if (item.coordinate) Object.entries(item.coordinate).forEach(([key, value]) => recurrence.push([key.replaceAll("_", " "), value]));
      recurrence.push(["nesting depth", item.depth]);
      intervalTip.innerHTML = `<div class="tip-name">${escapeHtml(item.name)}</div><div class="tip-op">${escapeHtml(item.op)} · ${escapeHtml(item.kind)}</div><div class="tip-big">${escapeHtml(fmtDuration(item.med_ms))}</div><div class="spark">${sparkline(item.dec_ms)}<div class="spark-labels"><span>P10 ${escapeHtml(fmtDuration(item.dec_ms[0]))}</span><span>P90 ${escapeHtml(fmtDuration(item.dec_ms[8]))}</span></div></div><div class="decile-grid">${item.dec_ms.map((value, index) => `<span>P${(index + 1) * 10}<b>${escapeHtml(fmtMs(value))}</b></span>`).join("")}</div><div class="tip-row"><span>samples</span><b>n=${item.n}</b></div><div class="tip-row"><span>representative</span><b>${escapeHtml(fmtDuration(item.rep_ms))}</b></div><div class="tip-row"><span>share of trial</span><b>${escapeHtml(fmtPct(item.med_ms, size.root_median_ms))}</b></div>${recurrence.map(([key, value]) => `<div class="tip-row"><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></div>`).join("")}<div class="tags">${item.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div>`;
      intervalTip.classList.add("on");
      moveIntervalTip(event);
    }

    function moveIntervalTip(event) {
      if (pinnedTooltip && event.type === "pointermove") return;
      const padding = 14;
      const rectangle = intervalTip.getBoundingClientRect();
      let left = event.clientX + padding;
      let top = event.clientY + padding;
      if (left + rectangle.width > innerWidth - 8) left = event.clientX - rectangle.width - padding;
      if (top + rectangle.height > innerHeight - 8) top = Math.max(8, event.clientY - rectangle.height - padding);
      intervalTip.style.left = `${Math.max(8, left)}px`;
      intervalTip.style.top = `${Math.max(8, top)}px`;
    }

    function hideIntervalTip(force) {
      if (pinnedTooltip && !force) return;
      intervalTip.classList.remove("on");
      if (force) pinnedTooltip = false;
    }

    function relatedArtifacts(item, size) {
      const names = [];
      if (/forest|fold/i.test(item.op)) names.push("folds", "merged_gkr");
      if (/presum|sumcheck/i.test(item.op)) names.push("presum");
      if (/ring/i.test(item.op)) names.push("ring");
      if (/ligerito|mq:lig/i.test(item.op)) names.push("ligerito");
      if (/serialize/i.test(item.op)) names.push("framing");
      return [...new Set(names)].filter(name => size.proof.artifacts[name]).map(name => [name, size.proof.artifacts[name]]);
    }

    function renderInspector(size) {
      const items = allIntervals(size);
      const selected = resolveSelection(size);
      const select = document.getElementById("interval-select");
      select.innerHTML = "";
      items.forEach(item => {
        const option = document.createElement("option");
        option.value = item.stable_key;
        option.selected = item.stable_key === selected.stable_key;
        option.textContent = `${item.name} — ${fmtDuration(item.med_ms)}`;
        select.appendChild(option);
      });
      select.onchange = () => {
        const item = items.find(candidate => candidate.stable_key === select.value);
        selectedKey = item.stable_key;
        selectedIdentity = eventIdentity(item);
        renderInspector(size);
        drawTimeline(size);
      };
      const artifacts = relatedArtifacts(selected, size);
      const detail = document.getElementById("interval-detail");
      const coordinate = selected.coordinate ? Object.entries(selected.coordinate).map(([key, value]) => `<span>${escapeHtml(key.replaceAll("_", " "))} <b>${escapeHtml(value)}</b></span>`).join("") : "";
      const mathExpressions = Array.isArray(selected.math) ? selected.math : [];
      detail.innerHTML = `<div class="inspect-title">${escapeHtml(selected.name)}</div><div class="inspect-op">${escapeHtml(selected.op)} · ${escapeHtml(selected.kind)}</div><div class="inspect-metrics"><span>P50 <b>${escapeHtml(fmtDuration(selected.med_ms))}</b></span><span>P10–P90 <b>${escapeHtml(fmtDuration(selected.dec_ms[0]))}–${escapeHtml(fmtDuration(selected.dec_ms[8]))}</b></span><span>representative <b>${escapeHtml(fmtDuration(selected.rep_ms))}</b></span><span>trial share <b>${escapeHtml(fmtPct(selected.med_ms, size.root_median_ms))}</b></span><span>samples <b>n=${selected.n}</b></span><span>depth <b>${selected.depth}</b></span>${coordinate}</div><div class="tags">${selected.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div><div class="math-list"></div>${artifacts.length ? `<div class="artifact-list">Related serialized components: ${artifacts.map(([name, stat]) => `${escapeHtml(name.replaceAll("_", " "))} <b>${escapeHtml(fmtBytes(stat.med))}</b> (P10–P90 ${escapeHtml(fmtBytes(stat.dec[0]))}–${escapeHtml(fmtBytes(stat.dec[8]))})`).join("<br>")}</div>` : ""}`;
      const mathList = detail.querySelector(".math-list");
      if (mathExpressions.length) mathExpressions.forEach(expression => {
        const row = document.createElement("div");
        row.textContent = expression;
        mathList.appendChild(row);
      }); else mathList.remove();
    }

    function drawPhaseTable(size) {
      const all = allIntervals(size);
      const primaryKeys = new Set(size.primary.map(item => item.stable_key));
      const output = [];
      size.primary.forEach(primary => {
        output.push({ item: primary, depth: 0 });
        all.filter(item => !primaryKeys.has(item.stable_key) && item.start_ms >= primary.start_ms - 1e-7 && item.end_ms <= primary.end_ms + 1e-7)
          .sort((a, b) => a.start_ms - b.start_ms || b.end_ms - a.end_ms || a.depth - b.depth)
          .forEach(item => output.push({ item, depth: Math.max(1, Math.min(4, item.depth - primary.depth)) }));
      });
      document.querySelector("#phase-table tbody").innerHTML = output.map(({ item, depth }) => `<tr><td><div class="step" style="--depth:${depth};--dot:${colorFor(item)}"><span class="dot"></span><span class="step-name">${escapeHtml(item.name)}</span></div></td><td class="num">${escapeHtml(fmtDuration(item.med_ms))}</td><td class="num">${escapeHtml(fmtDuration(item.dec_ms[0]))}–${escapeHtml(fmtDuration(item.dec_ms[8]))}</td><td class="num">${escapeHtml(fmtPct(item.med_ms, size.root_median_ms))}</td><td>${item.tags.map(tag => escapeHtml(tag)).join(" · ")}</td></tr>`).join("");
    }

    function paddedLogDomain(values) {
      const minimum = Math.min(...values), maximum = Math.max(...values);
      const padding = Math.max(.08, (Math.log(maximum) - Math.log(minimum)) * .07);
      return [Math.exp(Math.log(minimum) - padding), Math.exp(Math.log(maximum) + padding)];
    }

    function linearDomain(values) {
      const minimum = Math.min(...values), maximum = Math.max(...values), span = Math.max(maximum - minimum, maximum * .05);
      return [Math.max(0, minimum - span * .12), maximum + span * .12];
    }

    function interpolatedTicks(domain, count, logarithmic) {
      const [minimum, maximum] = domain;
      return Array.from({ length: count }, (_, index) => {
        const ratio = index / (count - 1);
        return logarithmic ? Math.exp(Math.log(minimum) + ratio * (Math.log(maximum) - Math.log(minimum))) : minimum + ratio * (maximum - minimum);
      });
    }

    function drawHeadlineChart() {
      const svg = document.getElementById("headline-chart");
      svg.querySelectorAll(":scope > :not(title):not(desc)").forEach(node => node.remove());
      const width = Math.max(320, svg.clientWidth || 900), height = width < 520 ? 470 : 430;
      const left = width < 520 ? 78 : 104, right = 22, top = 28, laneHeight = width < 520 ? 104 : 96, laneGap = 26;
      const plotWidth = width - left - right;
      svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
      svg.setAttribute("height", String(height));
      const x = exponent => left + (exponent - 20) / 10 * plotWidth;
      const points = HEADLINE.points;
      const lanes = [
        {
          title: "Time", subtitle: "ms · log scale", logarithmic: true,
          domain: paddedLogDomain(points.flatMap(point => [point.prover_ms, point.verifier_ms])),
          series: [
            { key: "prover_ms", color: "var(--c-prove)" },
            { key: "verifier_ms", color: "var(--c-verify)" },
          ],
          format: value => value >= 100 ? value.toFixed(0) : value >= 10 ? value.toFixed(1) : value.toFixed(2),
        },
        {
          title: "Proof size", subtitle: "KiB · linear scale", logarithmic: false,
          domain: linearDomain(points.map(point => point.proof_kib)),
          series: [{ key: "proof_kib", color: "var(--c-pcs)" }],
          format: value => value.toFixed(0),
        },
        {
          title: "Peak heap", subtitle: "MiB · log scale", logarithmic: true,
          domain: paddedLogDomain(points.map(point => point.prover_peak_heap_mib)),
          series: [{ key: "prover_peak_heap_mib", color: "var(--c-sum)" }],
          format: value => value >= 1000 ? `${(value / 1024).toFixed(1)}k` : value >= 100 ? value.toFixed(0) : value.toFixed(1),
        },
      ];
      const chartTop = top;
      const chartBottom = top + lanes.length * laneHeight + (lanes.length - 1) * laneGap;
      const selectedX = x(selectedExponent);
      svg.appendChild(svgNode("rect", { x: selectedX - Math.max(7, plotWidth / 42), y: chartTop, width: Math.max(14, plotWidth / 21), height: chartBottom - chartTop, class: "selected-band" }));
      lanes.forEach((lane, laneIndex) => {
        const yTop = top + laneIndex * (laneHeight + laneGap), yBottom = yTop + laneHeight;
        const y = value => {
          const ratio = lane.logarithmic ? (Math.log(value) - Math.log(lane.domain[0])) / (Math.log(lane.domain[1]) - Math.log(lane.domain[0])) : (value - lane.domain[0]) / (lane.domain[1] - lane.domain[0]);
          return yBottom - ratio * laneHeight;
        };
        svg.appendChild(svgNode("text", { x: 4, y: yTop + 13, class: "chart-title" }, lane.title));
        svg.appendChild(svgNode("text", { x: 4, y: yTop + 28, class: "chart-subtitle" }, lane.subtitle));
        interpolatedTicks(lane.domain, 4, lane.logarithmic).forEach(tick => {
          const py = y(tick);
          svg.appendChild(svgNode("line", { x1: left, y1: py, x2: width - right, y2: py, class: "chart-grid" }));
          svg.appendChild(svgNode("text", { x: left - 8, y: py + 4, class: "chart-axis", "text-anchor": "end" }, lane.format(tick)));
        });
        svg.appendChild(svgNode("rect", { x: left, y: yTop, width: plotWidth, height: laneHeight, class: "chart-frame" }));
        lane.series.forEach(series => {
          const path = points.map((point, index) => `${index === 0 ? "M" : "L"}${x(point.i).toFixed(2)},${y(point[series.key]).toFixed(2)}`).join(" ");
          svg.appendChild(svgNode("path", { d: path, class: "chart-line", stroke: series.color }));
          points.forEach(point => svg.appendChild(svgNode("circle", { cx: x(point.i), cy: y(point[series.key]), r: point.i === selectedExponent ? 4.2 : 3.2, fill: series.color, class: "chart-point" })));
        });
      });
      const tickStep = width < 480 ? 2 : 1;
      points.forEach(point => {
        if ((point.i - 20) % tickStep === 0 || point.i === 30) svg.appendChild(svgNode("text", { x: x(point.i), y: chartBottom + 22, class: "chart-axis", "text-anchor": "middle" }, String(point.i)));
      });
      svg.appendChild(svgNode("text", { x: left + plotWidth / 2, y: chartBottom + 42, class: "chart-title", "text-anchor": "middle" }, "Witness exponent i (bits = 2^i)"));
      const guideExponent = hoverGraphExponent ?? selectedExponent;
      const guide = svgNode("line", { x1: x(guideExponent), y1: chartTop, x2: x(guideExponent), y2: chartBottom, class: "hover-guide", "data-hover-guide": "true" });
      svg.appendChild(guide);
      const hit = svgNode("rect", { x: left, y: chartTop, width: plotWidth, height: chartBottom - chartTop, class: "chart-hit", "data-chart-hit": "true", "aria-label": "Move to inspect and click to select a witness exponent" });
      hit.addEventListener("pointermove", event => {
        const rectangle = svg.getBoundingClientRect();
        const localX = (event.clientX - rectangle.left) / rectangle.width * width;
        hoverGraphExponent = Math.max(20, Math.min(30, Math.round(20 + (localX - left) / plotWidth * 10)));
        guide.setAttribute("x1", x(hoverGraphExponent));
        guide.setAttribute("x2", x(hoverGraphExponent));
        showGraphTip(event, pointsByExponent.get(hoverGraphExponent));
      });
      hit.addEventListener("pointerleave", () => {
        hoverGraphExponent = null;
        graphTip.classList.remove("on");
        guide.setAttribute("x1", x(selectedExponent));
        guide.setAttribute("x2", x(selectedExponent));
      });
      hit.addEventListener("click", () => selectExponent(hoverGraphExponent ?? selectedExponent, { scroll: true }));
      svg.appendChild(hit);
    }

    function showGraphTip(event, point) {
      const card = document.querySelector(".headline-card");
      const cardRectangle = card.getBoundingClientRect();
      graphTip.innerHTML = `<div class="tip-head">2^${point.i} witness bits</div><div class="tip-row"><span>PCS prove P50</span><b>${point.prover_ms.toFixed(2)} ms</b></div><div class="tip-row"><span>Verifier P50</span><b>${point.verifier_ms.toFixed(2)} ms</b></div><div class="tip-row"><span>Proof size</span><b>${point.proof_bytes.toLocaleString()} B</b></div><div class="tip-row"><span>Peak tracked heap</span><b>${point.prover_peak_heap_mib.toFixed(2)} MiB</b></div>`;
      graphTip.classList.add("on");
      const tipRectangle = graphTip.getBoundingClientRect();
      let left = event.clientX - cardRectangle.left + 14;
      let top = event.clientY - cardRectangle.top + 14;
      if (left + tipRectangle.width > cardRectangle.width - 8) left -= tipRectangle.width + 28;
      if (top + tipRectangle.height > cardRectangle.height - 8) top -= tipRectangle.height + 28;
      graphTip.style.left = `${Math.max(8, left)}px`;
      graphTip.style.top = `${Math.max(8, top)}px`;
    }

    function renderHeadlineTable() {
      const body = document.querySelector("#headline-table tbody");
      body.innerHTML = HEADLINE.points.map(point => `<tr data-selected="${point.i === selectedExponent}"><td><button type="button" class="metric-link" data-exponent="${point.i}">2^${point.i}</button></td><td>${escapeHtml(point.resolved_ligerito)}</td><td class="num">${point.prover_ms.toFixed(2)}</td><td class="num">${point.verifier_ms.toFixed(2)}</td><td class="num">${point.proof_bytes.toLocaleString()}</td><td class="num">${point.proof_kib.toFixed(1)}</td><td class="num">${point.prover_peak_heap_mib.toFixed(2)}</td><td class="num">${point.commit_ms.toFixed(2)}</td></tr>`).join("");
      body.querySelectorAll("button[data-exponent]").forEach(button => button.addEventListener("click", () => selectExponent(Number(button.dataset.exponent), { scroll: true })));
    }

    function renderFooter(size) {
      const series = HEADLINE.series;
      document.getElementById("footer").innerHTML = `<b>Interval method.</b> ${size.warmup_n} unreported warmup + ${size.measured_n} measured trials. P10–P90 are ${escapeHtml(INTERVALS.quantile_method)}, not confidence intervals. Representative geometry comes from <code>${escapeHtml(size.representative_run_id)}</code>, sample ${size.representative_trial}, with scale ×${size.geometry_scale.toFixed(1)}.<br><b>Clean headline boundary.</b> ${escapeHtml(series.measurement_boundary)}. <b>Peak definition.</b> ${escapeHtml(series.peak_definition)}.<br><b>Configuration.</b> Requested <code>${escapeHtml(size.requested_config)}</code>; resolved <code>${escapeHtml(size.resolved_config)}</code>; ${size.threads} threads; 1-bit words.`;
    }

    function selectExponent(exponent, options = {}) {
      selectedExponent = exponent;
      hoverGraphExponent = null;
      hideIntervalTip(true);
      renderAll();
      if (options.scroll) document.getElementById("interval-explorer").scrollIntoView({ behavior: "smooth", block: "start" });
    }

    function renderAll() {
      const size = sizesByExponent.get(selectedExponent);
      resolveSelection(size);
      renderTabs();
      renderBadges(size);
      renderTiles(size);
      drawTimeline(size);
      renderInspector(size);
      drawPhaseTable(size);
      drawHeadlineChart();
      renderHeadlineTable();
      renderFooter(size);
    }

    document.addEventListener("click", event => {
      if (!event.target.closest("#timeline") && !event.target.closest("#interval-tip")) hideIntervalTip(true);
    });
    document.addEventListener("keydown", event => { if (event.key === "Escape") hideIntervalTip(true); });
    window.addEventListener("scroll", () => hideIntervalTip(true), { passive: true });
    const scheduleResize = () => {
      if (resizeFrame) cancelAnimationFrame(resizeFrame);
      resizeFrame = requestAnimationFrame(() => {
        resizeFrame = 0;
        drawTimeline(sizesByExponent.get(selectedExponent));
        drawHeadlineChart();
      });
    };
    if ("ResizeObserver" in window) {
      const observer = new ResizeObserver(scheduleResize);
      observer.observe(document.querySelector(".timeline-wrap"));
      observer.observe(document.querySelector(".headline-card"));
    } else window.addEventListener("resize", scheduleResize);
    renderAll();
  })();
  </script>
</body>
</html>
'''


def render_html(
    headline_payload: dict[str, Any], interval_payload: dict[str, Any]
) -> str:
    profile = escape_html_text(headline_payload["series"]["requested_config"])
    return (
        HTML_TEMPLATE.replace("__GENERATED_MARKER__", GENERATED_MARKER)
        .replace("__HEADLINE_DATA__", json_for_script(headline_payload))
        .replace("__INTERVAL_DATA__", json_for_script(interval_payload))
        .replace("__PROFILE_HTML__", profile)
    )


def write_generated(output: Path, content: str, *, adopt_existing: bool = False) -> None:
    """Atomically write output, refusing to clobber hand-authored files."""

    if output.is_symlink():
        raise DashboardError(f"refusing to replace symlink: {output}")
    if output.exists():
        try:
            prefix = output.read_text(encoding="utf-8")[:512]
        except UnicodeDecodeError as exc:
            raise DashboardError(f"refusing to replace non-text file: {output}") from exc
        if GENERATED_MARKER not in prefix and not adopt_existing:
            raise DashboardError(
                f"refusing to replace {output}: generated marker is absent; "
                "pass --adopt-existing for the intentional first replacement"
            )
        if GENERATED_MARKER not in prefix and output.suffix.lower() not in {".html", ".htm"}:
            raise DashboardError(f"refusing to adopt non-HTML destination: {output}")

    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", suffix=".tmp", dir=output.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    args = parse_args()
    try:
        with args.input.open(encoding="utf-8") as handle:
            headline = validate_payload(json.load(handle))
        with args.interval_input.open(encoding="utf-8") as handle:
            intervals = validate_interval_payload(json.load(handle))
        validate_cross_inputs(headline, intervals)
        html = render_html(headline, intervals)
        write_generated(args.output, html, adopt_existing=args.adopt_existing)
    except (DashboardError, json.JSONDecodeError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
