#!/usr/bin/env python3
"""LaTeX table of absolute numbers from a native-mul run (benches/mul_e2e_compare.rs).

Reads the `summary.json` of one or more `PerfRuns/<stamp>-native-mul` run
directories (later directories override earlier ones for the same scheme and
size, so a follow-up run of the large sizes extends a first run) and writes a self-documenting
`paper/native-mul-table.tex`: one row group per size N, one row per scheme, with
the medians of witness generation, the complete prover (commit included) and the
complete verifier, plus placeholder columns for proof size and peak memory.

    python3 scripts/native_mul_table.py PerfRuns/2026-09-08T20-07-32Z-native-mul PerfRuns/2026-09-08T20-55-10Z-native-mul
"""
from __future__ import annotations

import argparse
import datetime
import json
import platform
import subprocess
from pathlib import Path

SCHEMES = [  # (backend slug, LaTeX label)
    ("f2z", "\\ftwoz\\ (this work)"),
    ("binius64", "Binius64~\\cite{binius64}"),
    ("plonky3-whir", "Plonky3~\\cite{plonky} (WHIR)"),
]
PLACEHOLDER = "--"


def fmt_ms(v: float) -> str:
    if v >= 100:
        return f"{v:.0f}"
    if v >= 10:
        return f"{v:.1f}"
    return f"{v:.2f}"


def probe(cmd: list[str], default: str) -> str:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip() or default
    except Exception:
        return default


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run_dirs", type=Path, nargs="+", metavar="RUN_DIR")
    ap.add_argument("--out", type=Path, default=Path("paper/native-mul-table.tex"))
    ap.add_argument("--exponents", default="", help="comma list or lo-hi; default: every size in the run")
    ap.add_argument("--workload", default="u32")
    args = ap.parse_args()

    by = {}
    for run_dir in args.run_dirs:
        for r in json.loads((run_dir / "summary.json").read_text()):
            if r["workload"] == args.workload:
                r["run_dir"] = str(run_dir)
                by[(r["backend"], r["log_multiplications"])] = r
    rows = list(by.values())
    if not rows:
        raise SystemExit(f"no {args.workload} rows in {args.run_dirs}")
    exps = sorted({r["log_multiplications"] for r in rows})
    if args.exponents:
        if "-" in args.exponents:
            lo, hi = map(int, args.exponents.split("-"))
            exps = [e for e in exps if lo <= e <= hi]
        else:
            keep = {int(x) for x in args.exponents.split(",")}
            exps = [e for e in exps if e in keep]
    samples = sorted({r["samples"] for r in rows})
    run_list = " ".join(str(d) for d in args.run_dirs)
    cpu = probe(["sysctl", "-n", "machdep.cpu.brand_string"], platform.processor() or "unknown CPU")
    mem_gb = int(probe(["sysctl", "-n", "hw.memsize"], "0")) // (1 << 30)
    commit = probe(["git", "describe", "--always", "--dirty"], "unknown")
    date = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")

    out = []
    w = out.append
    w("% Native end-to-end u32-multiplication comparison (F2Z vs Binius64 vs Plonky3/WHIR) — GENERATED FILE, do not edit by hand.")
    w(f"% Generated by scripts/native_mul_table.py on {date} (UTC) at {commit} from {run_list} (benches/mul_e2e_compare.rs,")
    w("%   see docs/native-mul-compare.md; later run directories override earlier ones per scheme and size).")
    w("% Regenerate (from the repo root; this file is overwritten):")
    w(f"%   python3 scripts/native_mul_table.py {run_list}" + (f" --exponents {args.exponents}" if args.exponents else ""))
    w(f"% Machine: {cpu}, {mem_gb} GB; medians of {'/'.join(map(str, samples))} samples after one warm-up.")
    w("% Columns: witgen = witness_ms (native witness generation; Binius64 packs its witness inside its prover, so its witgen")
    w("%   overlaps the prover column); prover = online_prover_ms (the complete native prover call after witness generation,")
    w("%   i.e. commitment + PIOP + PCS opening); verifier = verify_ms; proof size and peak memory are PLACEHOLDERS (--).")
    w("% Bold = best of the three schemes for that size and column.")
    w("% Medians (ms) as recorded in summary.json (`--` rows below = scheme not run at that size):")
    for e in exps:
        for slug, _ in SCHEMES:
            r = by.get((slug, e))
            if r:
                m = r["medians"]
                w(f"%   2^{e} {slug:13s} witness={m['witness_ms']:.3f} commit={m['commit_ms']:.3f} piop={m['piop_ms']:.3f} opening={m['opening_ms']:.3f} "
                  f"online_prover={m['online_prover_ms']:.3f} witness_to_proof={m['witness_to_proof_ms']:.3f} verify={m['verify_ms']:.3f} setup={r['setup_ms']:.3f} "
                  f"samples={r['samples']} run={Path(r['run_dir']).name}")
            else:
                w(f"%   2^{e} {slug:13s} not run")
    missing = {}
    for slug, label in SCHEMES:
        gone = [e for e in exps if (slug, e) not in by]
        if gone and len(gone) < len(exps):
            missing[slug] = gone
    w("")
    w("\\begin{table}[H]")
    w("  \\centering")
    w("  \\small")
    w("  \\setlength{\\tabcolsep}{4.5pt}")
    w("  \\begin{tabular}{@{}rlrrrrr@{}}")
    w("    \\toprule")
    w("    $N$ & Scheme & Witgen (ms) & Prover (ms) & Verifier (ms) & Proof (KB) & Peak mem.\\ (GB) \\\\")
    w("    \\midrule")
    for gi, e in enumerate(exps):
        present = {slug: by[(slug, e)]["medians"] for slug, _ in SCHEMES if (slug, e) in by}
        best = {k: min(m[k] for m in present.values()) for k in ("witness_ms", "online_prover_ms", "verify_ms")}
        for ri, (slug, label) in enumerate(SCHEMES):
            n_cell = f"$2^{{{e}}}$" if ri == 0 else ""
            m = present.get(slug)
            if m is None:
                w(f"    {n_cell} & {label} & {PLACEHOLDER} & {PLACEHOLDER} & {PLACEHOLDER} & {PLACEHOLDER} & {PLACEHOLDER} \\\\")
                continue
            cells = []
            for k in ("witness_ms", "online_prover_ms", "verify_ms"):
                s = fmt_ms(m[k])
                cells.append(f"\\textbf{{{s}}}" if m[k] == best[k] and len(present) > 1 else s)
            w(f"    {n_cell} & {label} & {cells[0]} & {cells[1]} & {cells[2]} & {PLACEHOLDER} & {PLACEHOLDER} \\\\")
        if gi + 1 < len(exps):
            w("    \\addlinespace")
    w("    \\bottomrule")
    w("  \\end{tabular}")
    w("  \\caption{Native end-to-end proofs of $N$ multiplications $x \\cdot y = z$ of random $32$-bit integers: "
      "\\ftwoz\\ (Spartan over a transcript-sampled prime with the \\ftwoz\\ opening, $\\lambda = 100$), "
      "Binius64 (native multiplication and bit constraints, ring switching and BaseFold at rate $1/2$ with $241$ queries for $100$ bits), "
      "and Plonky3 (Goldilocks AIR with $32$-bit decompositions, WHIR over a degree-$5$ extension at rate $1/2$, $100$ bits). "
      "\\emph{Witgen} is the native witness generation; \\emph{prover} is the complete prover call after witness generation, "
      "commitment included; \\emph{verifier} is the complete verification. "
      + "".join(f"{dict(SCHEMES)[slug].split('~')[0].replace(chr(92) + 'ftwoz' + chr(92), chr(92) + 'ftwoz')} was not run at " + ", ".join(f"$2^{{{e}}}$" for e in gone) + ". " for slug, gone in missing.items())
      + f"{cpu}, {mem_gb}\\,GB, $8$ threads; medians of {samples[0]} runs after one warm-up.}}")
    w("  \\label{tab:native-mul}")
    w("\\end{table}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(exps)} sizes, {len(SCHEMES)} schemes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
