#!/usr/bin/env python3
"""Ratio figures (BitZ / x, x ∈ {Binius64, Plonky3 WHIR}) from a native-mul run.

Reads `PerfRuns/<stamp>-native-mul/{summary.json,samples.jsonl}` produced by
`benches/mul_e2e_compare.rs` and writes, per metric, a standalone pgfplots
figure (`.tex`, compiled to `.pdf` with `--compile`) plus one CSV with every
value and ratio:

  prover    — `online_prover_ms` medians: the complete native prover call after
              witness generation, i.e. commit + PIOP + PCS opening;
  verifier  — `verify_ms` medians;
  proof     — median `proof_bytes` over the measured samples.  The bench leaves
              BitZ's `proof_bytes` unset, so supply them with
              `--bitz-proof-bytes 15=157000,16=185764,...` (bytes per exponent,
              e.g. from `bitz --mul <e> --profile udr`, the same relation and
              opener the bench uses).

Ratios below 1 mean BitZ is faster / smaller than x.
"""
from __future__ import annotations

import argparse
import csv
import json
import shutil
import statistics
import subprocess
from collections import defaultdict
from pathlib import Path

BACKENDS = {"binius64": "Binius64", "plonky3-whir": "Plonky3 WHIR"}
# Categorical slots 1 and 2 of the validated reference palette (light surface).
SERIES_COLORS = {"binius64": "2a78d6", "plonky3-whir": "eb6834"}
METRICS = {
    "prover": ("Prover time (incl.\\ commit), BitZ / $x$", "ms"),
    "verifier": ("Verifier time, BitZ / $x$", "ms"),
    "proof": ("Proof size, BitZ / $x$", "bytes"),
}


def load_run(run_dir: Path, bitz_proof_bytes: dict[int, int]) -> dict[str, dict[int, dict[str, float]]]:
    """{backend: {exponent: {prover, verifier, proof}}} (medians)."""
    data: dict[str, dict[int, dict[str, float]]] = defaultdict(dict)
    for row in json.loads((run_dir / "summary.json").read_text()):
        med = row["medians"]
        data[row["backend"]][row["log_multiplications"]] = {
            "prover": med["online_prover_ms"],
            "verifier": med["verify_ms"],
        }
    proof: dict[tuple[str, int], list[int]] = defaultdict(list)
    for line in (run_dir / "samples.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        if rec["trial"].get("kind") == "warmup":
            continue
        pb = rec["metrics"].get("proof_bytes")
        if pb is not None:
            proof[(rec["backend"], rec["log_multiplications"])].append(pb)
    for (backend, exp), values in proof.items():
        data[backend][exp]["proof"] = statistics.median(values)
    for exp, nbytes in bitz_proof_bytes.items():
        if exp in data.get("bitz", {}):
            data["bitz"][exp]["proof"] = float(nbytes)
    return data


def fmt_ratio(r: float) -> str:
    if r >= 10:
        return f"{r:.0f}"
    if r >= 1:
        return f"{r:.1f}"
    if r >= 0.1:
        return f"{r:.2f}"
    return f"{r:.3f}"


def nice_log_ticks(vmin: float, vmax: float) -> list[float]:
    """Round tick values covering [vmin, vmax]: 1-2-5 steps for narrow ranges, 1-3 steps for wide ones."""
    import math
    candidates = []
    fine = vmax / vmin < 8
    for dec in range(-4, 3):
        for m in ((1, 1.5, 2, 3, 4, 5, 6, 8) if fine else (1, 3)):
            candidates.append(m * 10 ** dec)
    ticks = [t for t in candidates if vmin * 0.92 <= t <= vmax * 1.08]
    return ticks or [10 ** math.floor(math.log10(vmin)), 10 ** math.ceil(math.log10(vmax))]


def fmt_tick(t: float) -> str:
    return f"{t:g}"


def figure_tex(metric: str, ylabel: str, series: dict[str, list[tuple[int, float]]], exps: list[int]) -> str:
    lo, hi = min(exps), max(exps)
    values = [v for pts in series.values() for _, v in pts] + [1.0]  # the parity line is always in view
    ticks = nice_log_ticks(min(values), max(values))
    ytick = ",".join(f"{t:g}" for t in ticks)
    yticklabels = ",".join(fmt_tick(t) for t in ticks)
    xticks = ",".join(str(e) for e in exps)
    xlabels = ",".join(f"$2^{{{e}}}$" for e in exps)
    plots = []
    legend = []
    for key, points in series.items():
        color = SERIES_COLORS[key]
        coords = " ".join(f"({e},{v:.6g})" for e, v in points)
        last_e, last_v = points[-1]
        plots.append(
            f"    \\addplot[color=s{key.replace('-', '')}, line width=1.5pt, mark=*, mark size=2.6pt,\n"
            f"      mark options={{fill=s{key.replace('-', '')}, draw=surface, line width=1.2pt}}]\n"
            f"      coordinates {{{coords}}}\n"
            f"      node[pos=1, anchor=west, xshift=4pt, font=\\scriptsize, text=black] {{{fmt_ratio(last_v)}$\\times$}};"
        )
        legend.append(f"BitZ / {BACKENDS[key]}")
    color_defs = "\n".join(
        f"\\definecolor{{s{k.replace('-', '')}}}{{HTML}}{{{c}}}" for k, c in SERIES_COLORS.items()
    )
    legend_entries = ", ".join(legend)
    return f"""% Generated by scripts/native_mul_ratio_figures.py — {metric} ratio figure. Do not edit by hand.
\\documentclass[tikz,border=3pt]{{standalone}}
\\usepackage{{pgfplots}}
\\pgfplotsset{{compat=1.18}}
{color_defs}
\\definecolor{{surface}}{{HTML}}{{FFFFFF}}
\\definecolor{{gridgray}}{{HTML}}{{E3E3E0}}
\\definecolor{{axisgray}}{{HTML}}{{9A9A96}}
\\definecolor{{textmuted}}{{HTML}}{{52514E}}
\\begin{{document}}
\\begin{{tikzpicture}}
  \\begin{{axis}}[
    width=9.2cm, height=6.2cm,
    xlabel={{$\\log_2 N$ (u32 multiplications)}},
    ylabel={{{ylabel}}},
    ymode=log, log basis y=10,
    ytick={{{ytick}}}, yticklabels={{{yticklabels}}},
    xmin={lo - 0.35}, xmax={hi + 0.35},
    ymin={min(values) / 1.25:.6g}, ymax={max(values) * 1.25:.6g},
    xtick={{{xticks}}}, xticklabels={{{xlabels}}},
    grid=major, grid style={{solid, gridgray, line width=0.4pt}},
    axis line style={{axisgray, line width=0.4pt}},
    tick style={{axisgray, line width=0.4pt}},
    tick label style={{font=\\footnotesize, text=textmuted}},
    label style={{font=\\small}},
    legend style={{draw=none, fill=none, font=\\footnotesize, cells={{anchor=west}}, at={{(0.5,-0.30)}}, anchor=north, legend columns=-1, /tikz/every even column/.append style={{column sep=0.7cm}}}},
    clip=false,
  ]
    % parity: BitZ equal to x
    \\addplot[axisgray, line width=0.5pt, forget plot, domain={lo - 0.35}:{hi + 0.35}, samples=2] {{1}}
      node[pos=0, anchor=north west, font=\\scriptsize, text=textmuted, inner sep=2pt] {{parity}};
{chr(10).join(plots)}
    \\legend{{{legend_entries}}}
  \\end{{axis}}
\\end{{tikzpicture}}
\\end{{document}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run_dir", type=Path, help="PerfRuns/<stamp>-native-mul directory")
    ap.add_argument("--out-dir", type=Path, default=Path("paper/figures"))
    ap.add_argument("--prefix", default="native-mul-ratio")
    ap.add_argument("--bitz-proof-bytes", default="", help="e=bytes,e=bytes,... for BitZ (not recorded by the bench)")
    ap.add_argument("--compile", action="store_true", help="run pdflatex on each figure (and pdftoppm previews if present)")
    args = ap.parse_args()

    bitz_pb = {}
    if args.bitz_proof_bytes:
        for item in args.bitz_proof_bytes.split(","):
            e, b = item.split("=")
            bitz_pb[int(e)] = int(b)
    data = load_run(args.run_dir, bitz_pb)
    if "bitz" not in data:
        raise SystemExit("run has no bitz rows")
    exps = sorted(data["bitz"])
    args.out_dir.mkdir(parents=True, exist_ok=True)

    # CSV with every value and ratio.
    csv_path = args.out_dir / f"{args.prefix}s.csv"
    with csv_path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["metric", "unit", "log2_n", "bitz", "binius64", "plonky3-whir", "bitz_over_binius64", "bitz_over_plonky3-whir"])
        for metric, (_, unit) in METRICS.items():
            for e in exps:
                f = data["bitz"][e].get(metric)
                vals = [data.get(b, {}).get(e, {}).get(metric) for b in BACKENDS]
                w.writerow([metric, unit, e, f] + vals + [None if (f is None or v is None) else f / v for v in vals])

    written = []
    for metric, (ylabel, _) in METRICS.items():
        series = {}
        for key in BACKENDS:
            pts = []
            for e in exps:
                f = data["bitz"][e].get(metric)
                v = data.get(key, {}).get(e, {}).get(metric)
                if f is not None and v is not None:
                    pts.append((e, f / v))
            if pts:
                series[key] = pts
        if not series:
            print(f"{metric}: no ratios available (missing values); skipped")
            continue
        tex_path = args.out_dir / f"{args.prefix}-{metric}.tex"
        tex_path.write_text(figure_tex(metric, ylabel, series, exps))
        written.append(tex_path)
        print(f"wrote {tex_path}")
    print(f"wrote {csv_path}")

    if args.compile:
        for tex_path in written:
            run = subprocess.run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_path.name],
                                 cwd=args.out_dir, capture_output=True, text=True)
            if run.returncode != 0:
                tail = "\n".join(run.stdout.splitlines()[-25:])
                raise SystemExit(f"pdflatex failed on {tex_path.name}:\n{tail}")
            for ext in ("aux", "log"):
                (args.out_dir / f"{tex_path.stem}.{ext}").unlink(missing_ok=True)
            pdf = args.out_dir / f"{tex_path.stem}.pdf"
            print(f"compiled {pdf}")
            if shutil.which("pdftoppm"):
                subprocess.run(["pdftoppm", "-r", "160", "-png", "-singlefile", str(pdf), str(args.out_dir / tex_path.stem)], check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
