//! Public SHA-256 compression constraints and their batch geometry.
//!
//! The symbolic circuit is replayed exactly once. Its local CSC matrices are
//! retained once, while independent compression batches are represented by a
//! tensor repetition over the instance coordinate.

use std::sync::OnceLock;

use blake3::Hasher;
use circuit::constraints::SparseMatrix as CircuitSparseMatrix;
use circuit::{
    constraints::ConstraintGenerator,
    sha256::{COMPRESSION_INPUT_BITS, compression_circuit},
};
use crypto_primitives::{PrimeField, crypto_bigint_monty::F128, crypto_bigint_uint::Uint};
use num_bigint::{BigInt, BigUint, Sign};
use thiserror::Error;

use crate::{
    f2map::{PackedRepeatedVirtualMap, PreparedVirtualMap, PreparedVirtualMapError},
    pcs::IntEvalParams,
    sparse_matrix::SparseMatrix,
};

use super::super::{
    ConstraintMatrices, PreparedConstraintMatrices, SpartanField, SpartanMatrixError,
    f2z::SpartanF2zField,
    profile::{IopSecurityParams, IopSecurityProfile, Lambda100, ProfileError},
};
use super::prime::{
    SHA256_MAX_LOG_COMPRESSIONS, SHA256_MIN_LOG_COMPRESSIONS, Sha256PrimeError, Sha256PrimeProfile,
    sha256_instance_facts,
};

/// Live Boolean source bits generated by one compression.
pub const SHA256_F_LIVE_BITS: usize = 7_144;
/// Source bits after adding the public constant-one coordinate.
pub const SHA256_F_BAR_LIVE_BITS: usize = SHA256_F_LIVE_BITS + 1;
/// Per-compression source width after removing the shared constant cell.
pub const SHA256_F_INSTANCE_BITS: usize = SHA256_F_BAR_LIVE_BITS - 1;
/// Power-of-two width of the padded one-instance local source matrix.
pub const SHA256_F_STRIDE: usize = 1 << SHA256_F_LOCAL_VARS;
/// Local source-coordinate width.
pub const SHA256_F_LOCAL_VARS: usize = 13;

/// Live integer-assignment bits, including its leading constant one.
pub const SHA256_H_BAR_LIVE_BITS: usize = 20_457;
/// Per-compression assignment width after removing the shared constant cell.
pub const SHA256_H_INSTANCE_BITS: usize = SHA256_H_BAR_LIVE_BITS - 1;
/// Power-of-two width of the padded one-instance local assignment matrix.
pub const SHA256_H_STRIDE: usize = 1 << SHA256_H_LOCAL_VARS;
/// Local assignment-coordinate width.
pub const SHA256_H_LOCAL_VARS: usize = 15;

/// Number of public words in one compression statement: state, block, output.
pub(crate) const SHA256_PUBLIC_WORDS: usize = 32;
/// Bit width of every public SHA-256 word.
pub(crate) const SHA256_PUBLIC_WORD_BITS: usize = 32;
/// Returns the local integer-assignment column for one public statement bit.
///
/// Word slots use canonical statement order: state `[0, 8)`, block `[8, 24)`,
/// then output `[24, 32)`. Bits within each word are least-significant first.
pub(crate) const fn sha256_public_h_column(word_slot: usize, bit: usize) -> usize {
    assert!(word_slot < SHA256_PUBLIC_WORDS);
    assert!(bit < SHA256_PUBLIC_WORD_BITS);

    match word_slot {
        0..8 => 1 + 32 * word_slot + bit,
        8..24 => 257 + 32 * (word_slot - 8) + bit,
        _ => 20_193 + 33 * (word_slot - 24) + bit,
    }
}

/// Returns the local committed-source column for one public statement bit.
///
/// This uses the same word and bit order as [`sha256_public_h_column`].
pub(crate) const fn sha256_public_f_column(word_slot: usize, bit: usize) -> usize {
    assert!(word_slot < SHA256_PUBLIC_WORDS);
    assert!(bit < SHA256_PUBLIC_WORD_BITS);

    match word_slot {
        0..8 => 513 + 32 * word_slot + bit,
        8..24 => 1 + 32 * (word_slot - 8) + bit,
        _ => 6_881 + 33 * (word_slot - 24) + bit,
    }
}

/// Live rank-1 constraints generated by one compression.
pub const SHA256_CONSTRAINTS: usize = 184;
/// Padded constraint-row stride.
pub const SHA256_CONSTRAINT_STRIDE: usize = 1 << SHA256_CONSTRAINT_LOCAL_VARS;
/// Local constraint-row coordinate width.
pub const SHA256_CONSTRAINT_LOCAL_VARS: usize = 8;

/// Failures while compiling or repeating the public SHA-256 relation.
#[derive(Debug, Error)]
pub enum Sha256ConstraintError {
    /// The requested batch or packed global domain is empty or does not fit
    /// the host index type.
    #[error("SHA-256 batch geometry is invalid or too large")]
    InvalidBatchExponent,

    /// The outer instance capacity is outside the runtime-prime protocol's
    /// supported production window.
    #[error(
        "SHA-256 runtime-prime protocol requires log-instance-capacity in [7, 16], got {actual}"
    )]
    UnsupportedInstanceCapacityExponent { actual: usize },

    /// The selected security profile asks the validated UDR backend for an
    /// unsupported round-by-round target.
    #[error("SHA-256 Ligerito target must be in [64, 128] bits, got {actual}")]
    UnsupportedLigeritoTargetBits { actual: usize },

    /// The selected security profile is incompatible with the single
    /// transcript-derived-prime SHA protocol.
    #[error(transparent)]
    PrimeProfile(#[from] Sha256PrimeError),

    /// Generated R1CS matrices did not prepare successfully.
    #[error(transparent)]
    Spartan(#[from] SpartanMatrixError),

    /// Generated Boolean map metadata did not prepare successfully.
    #[error(transparent)]
    VirtualMap(#[from] PreparedVirtualMapError),

    /// The canonical integer-relation digest cannot encode this host shape.
    #[error("SHA-256 integer relation dimensions do not fit the canonical encoding")]
    IntegerRelationTooLarge,

    /// The security profile could not be instantiated at this shape.
    #[error(transparent)]
    Profile(#[from] ProfileError),
}

/// A q-independent SHA-256 compression relation prepared for a packed batch.
///
/// The exact signed integer matrices and local Boolean map are synthesized
/// once and shared by every batch. The committed source and derived assignment
/// share one constant, concatenate all live instances, and pad only their
/// complete global domains. The prover and verifier project this retained
/// relation only after the commitment-bound transcript selects a runtime prime.
#[derive(Clone, Debug)]
pub struct PreparedSha256CompressionBatch {
    local: &'static IntegerLocalRelation,
    map: PackedRepeatedVirtualMap,
    p_f: IntEvalParams,
    p_h: IntEvalParams,
    instances: usize,
    log_instance_capacity: usize,
    security: IopSecurityParams,
}

impl PreparedSha256CompressionBatch {
    /// Projects the exact signed coefficients into a validated runtime prime
    /// field. The q-independent relation and its digest remain unchanged.
    pub(super) fn project(
        &self,
        field_config: &<F128 as PrimeField>::Config,
    ) -> Result<PreparedConstraintMatrices<SpartanF2zField>, Sha256ConstraintError> {
        project_integer_relation(&self.local.matrices, field_config)
    }

    /// Canonical digest of the exact integer matrices and local Boolean map.
    pub const fn integer_relation_digest(&self) -> &[u8; 32] {
        &self.local.digest
    }

    /// Repeated Boolean map for the complete compression batch.
    pub const fn map(&self) -> &PackedRepeatedVirtualMap {
        &self.map
    }

    /// Number of live independent compression instances.
    pub const fn instances(&self) -> usize {
        self.instances
    }

    /// Logarithm of the power-of-two outer Spartan instance capacity.
    pub const fn log_instance_capacity(&self) -> usize {
        self.log_instance_capacity
    }

    /// F2Z geometry of the committed Boolean source rows.
    pub const fn source_params(&self) -> &IntEvalParams {
        &self.p_f
    }

    /// F2Z geometry of the synthesized Boolean assignment rows.
    pub const fn assignment_params(&self) -> &IntEvalParams {
        &self.p_h
    }

    /// Conservative maximum of
    /// `sum(|A_i|) sum(|B_i|) + sum(|C_i|)` over local constraint rows.
    /// For a Boolean assignment this bounds the magnitude of every exact
    /// integer R1CS residual before reduction modulo q.
    pub fn max_boolean_residual_bound(&self) -> &BigUint {
        &self.local.max_boolean_residual_bound
    }

    /// The instantiated security parameters and their accounting.
    pub const fn security(&self) -> &IopSecurityParams {
        &self.security
    }
}

#[derive(Debug)]
struct IntegerLocalRelation {
    matrices: ConstraintMatrices<BigInt>,
    map: PreparedVirtualMap,
    digest: [u8; 32],
    max_boolean_residual_bound: BigUint,
}

static INTEGER_LOCAL_RELATION: OnceLock<IntegerLocalRelation> = OnceLock::new();

/// Prepares the q-independent public relation for
/// `2^log_compressions` independent SHA-256 compression invocations at the
/// DEFAULT security profile, [`Lambda100`] (no grinding anywhere; every
/// term this crate controls ≥ 100 bits). Use
/// [`prepare_sha256_compression_batch_with_profile`] to select
/// `Lambda128` or the historical `Sha128ReferenceSchedule`.
/// Supported exponents are [`SHA256_MIN_LOG_COMPRESSIONS`] through
/// [`SHA256_MAX_LOG_COMPRESSIONS`], inclusive.
///
/// No runtime modulus is consulted here. The proof flow commits to the Boolean
/// source rows before deriving `q` and internally projecting this relation.
pub fn prepare_sha256_compression_batch(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_batch_with_profile::<Lambda100>(log_compressions)
}

/// [`prepare_sha256_compression_batch`] under an explicit
/// single-prime security profile: the profile's interval and grinding
/// schedule are instantiated here and drive the whole prove/verify path.
pub fn prepare_sha256_compression_batch_with_profile<P: IopSecurityProfile>(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let instances = validate_batch_exponent(log_compressions)?;
    validate_instance_capacity(instances)?;
    let prepared = prepare_sha256_compression_instances_with_profile::<P>(instances)?;
    validate_prepared_protocol(&prepared)?;
    Ok(prepared)
}

/// Prepares the largest packed batch whose assignment witness fits exactly
/// inside `2^log_assignment_rows` cells.
///
/// Each compression contributes [`SHA256_H_INSTANCE_BITS`] cells and the
/// entire batch shares one leading constant cell.  Any unused cells form one
/// trailing zero suffix; there is no per-instance padding. The resulting
/// next-power-of-two instance capacity must lie in the same supported window
/// as [`prepare_sha256_compression_batch`].
pub fn prepare_sha256_compression_batch_for_assignment_rows(
    log_assignment_rows: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    prepare_sha256_compression_batch_for_assignment_rows_with_profile::<Lambda100>(
        log_assignment_rows,
    )
}

/// [`prepare_sha256_compression_batch_for_assignment_rows`] under an explicit
/// security profile.
pub fn prepare_sha256_compression_batch_for_assignment_rows_with_profile<P: IopSecurityProfile>(
    log_assignment_rows: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let rows = 1usize
        .checked_shl(
            u32::try_from(log_assignment_rows)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    let instances = rows
        .checked_sub(1)
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        / SHA256_H_INSTANCE_BITS;
    if instances == 0 {
        return Err(Sha256ConstraintError::InvalidBatchExponent);
    }
    validate_instance_capacity(instances)?;
    let prepared = prepare_sha256_compression_instances_with_profile::<P>(instances)?;
    validate_prepared_protocol(&prepared)?;
    if prepared.p_h.t != log_assignment_rows {
        return Err(Sha256ConstraintError::InvalidBatchExponent);
    }
    Ok(prepared)
}

#[cfg(test)]
pub(super) fn prepare_sha256_compression_batch_for_test(
    log_compressions: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let instances = validate_batch_exponent(log_compressions)?;
    prepare_sha256_compression_instances_with_profile::<Lambda100>(instances)
}

fn prepare_sha256_compression_instances_with_profile<P: IopSecurityProfile>(
    instances: usize,
) -> Result<PreparedSha256CompressionBatch, Sha256ConstraintError> {
    let log_instance_capacity = instances
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        .ilog2() as usize;
    let exponent = u32::try_from(log_instance_capacity)
        .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?;
    let local = integer_local_relation();
    let source_vars = packed_domain_vars(instances, SHA256_F_INSTANCE_BITS)?;
    let assignment_vars = packed_domain_vars(instances, SHA256_H_INSTANCE_BITS)?;
    let p_f = IntEvalParams {
        t: source_vars,
        s: 0,
        word_bits: 1,
    };
    let p_h = IntEvalParams {
        t: assignment_vars,
        s: 0,
        word_bits: 1,
    };
    let map =
        PackedRepeatedVirtualMap::new(local.map.clone(), instances, p_h.cells(), p_f.cells())?;
    let mut facts = sha256_instance_facts(exponent);
    facts.opening_t =
        u32::try_from(assignment_vars).map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?;
    let security = P::instantiate(&facts)?;
    Ok(PreparedSha256CompressionBatch {
        local,
        map,
        p_f,
        p_h,
        instances,
        log_instance_capacity,
        security,
    })
}

fn validate_batch_exponent(log_compressions: usize) -> Result<usize, Sha256ConstraintError> {
    let instances = 1usize
        .checked_shl(
            u32::try_from(log_compressions)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    SHA256_H_STRIDE
        .checked_mul(instances)
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    Ok(instances)
}

fn validate_instance_capacity(instances: usize) -> Result<(), Sha256ConstraintError> {
    let log_instance_capacity = instances
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?
        .ilog2() as usize;
    if !(SHA256_MIN_LOG_COMPRESSIONS..=SHA256_MAX_LOG_COMPRESSIONS).contains(&log_instance_capacity)
    {
        return Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent {
            actual: log_instance_capacity,
        });
    }
    Ok(())
}

fn validate_prepared_protocol(
    prepared: &PreparedSha256CompressionBatch,
) -> Result<(), Sha256ConstraintError> {
    Sha256PrimeProfile::from_security(&prepared.security, prepared.log_instance_capacity)?;
    let target = prepared.security.ligerito_target_bits;
    if !(64..=128).contains(&target) {
        return Err(Sha256ConstraintError::UnsupportedLigeritoTargetBits { actual: target });
    }
    Ok(())
}

fn packed_domain_vars(
    instances: usize,
    instance_width: usize,
) -> Result<usize, Sha256ConstraintError> {
    let live = instance_width
        .checked_mul(instances)
        .and_then(|cells| cells.checked_add(1))
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    let domain = live
        .checked_next_power_of_two()
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    Ok(domain.ilog2() as usize)
}

fn integer_local_relation() -> &'static IntegerLocalRelation {
    INTEGER_LOCAL_RELATION.get_or_init(|| {
        build_integer_local_relation().expect("the static SHA-256 compression relation is valid")
    })
}

fn build_integer_local_relation() -> Result<IntegerLocalRelation, Sha256ConstraintError> {
    let mut generator = ConstraintGenerator::new(COMPRESSION_INPUT_BITS);
    let inputs = generator.inputs();
    let output = compression_circuit(&mut generator, &inputs);
    let generated = generator.into_matrices();

    assert_eq!(generated.m.row_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.m.column_count(), SHA256_F_BAR_LIVE_BITS);
    assert_eq!(generated.a.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.b.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.c.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.a.column_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.m.rows()[0].positions(), &[0]);

    for word_slot in 0..SHA256_PUBLIC_WORDS {
        for bit in 0..SHA256_PUBLIC_WORD_BITS {
            let h_column = sha256_public_h_column(word_slot, bit);
            let f_column = sha256_public_f_column(word_slot, bit);
            assert_eq!(generated.m.rows()[h_column].positions(), &[f_column]);

            if word_slot >= 24 {
                let output_bit = &output[(word_slot - 24) * SHA256_PUBLIC_WORD_BITS + bit];
                assert!(!output_bit.constant());
                assert_eq!(output_bit.witnesses().len(), 1);
                assert!(output_bit.witnesses().contains(&(f_column - 1)));
            }
        }
    }

    let a = convert_integer_matrix(&generated.a)?;
    let b = convert_integer_matrix(&generated.b)?;
    let c = convert_integer_matrix(&generated.c)?;
    let matrices = ConstraintMatrices::new(a, b, c)?;

    let map_rows = generated
        .m
        .rows()
        .iter()
        .map(|row| {
            row.positions()
                .iter()
                .copied()
                .map(|column| (column, true))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    let map = SparseMatrix::try_from_rows(SHA256_F_BAR_LIVE_BITS, map_rows)
        .map_err(SpartanMatrixError::from)?;
    let map = PreparedVirtualMap::new(map)?;
    let max_boolean_residual_bound = max_boolean_residual_bound(&matrices);
    let digest = integer_relation_digest(&matrices, &map)?;

    Ok(IntegerLocalRelation {
        matrices,
        map,
        digest,
        max_boolean_residual_bound,
    })
}

fn convert_integer_matrix(
    matrix: &CircuitSparseMatrix<BigInt>,
) -> Result<SparseMatrix<BigInt>, SpartanMatrixError> {
    debug_assert!(matrix.row_count() <= SHA256_CONSTRAINT_STRIDE);
    debug_assert!(matrix.column_count() <= SHA256_H_STRIDE);

    let mut rows = matrix
        .rows()
        .iter()
        .map(|row| {
            row.entries()
                .iter()
                .map(|(column, coefficient)| (*column, coefficient.clone()))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    rows.resize_with(SHA256_CONSTRAINT_STRIDE, Vec::new);
    SparseMatrix::try_from_rows(SHA256_H_STRIDE, rows).map_err(SpartanMatrixError::from)
}

fn project_integer_relation(
    matrices: &ConstraintMatrices<BigInt>,
    field_config: &<F128 as PrimeField>::Config,
) -> Result<PreparedConstraintMatrices<SpartanF2zField>, Sha256ConstraintError> {
    <SpartanF2zField as SpartanField>::validate_config(field_config)
        .map_err(SpartanMatrixError::from)?;
    let modulus = BigInt::from(BigUint::from_bytes_le(
        &SpartanF2zField::canonical_modulus_encoding(field_config),
    ));
    let project =
        |matrix: &SparseMatrix<BigInt>| -> Result<SparseMatrix<F128>, SpartanMatrixError> {
            let columns = matrix
                .columns()
                .map(|column| {
                    column
                        .into_iter()
                        .map(|(row, coefficient)| {
                            (row, bigint_to_field(coefficient, &modulus, field_config))
                        })
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>();
            SparseMatrix::try_from_columns(matrix.row_count(), columns)
                .map_err(SpartanMatrixError::from)
        };
    let matrices = ConstraintMatrices::new(
        project(matrices.a())?,
        project(matrices.b())?,
        project(matrices.c())?,
    )?;
    PreparedConstraintMatrices::new(matrices, field_config).map_err(Sha256ConstraintError::from)
}

fn bigint_to_field(
    value: &BigInt,
    modulus: &BigInt,
    field_config: &<F128 as PrimeField>::Config,
) -> F128 {
    let mut reduced = value % modulus;
    if reduced.sign() == Sign::Minus {
        reduced += modulus;
    }
    let words = reduced
        .to_biguint()
        .expect("a reduced coefficient is nonnegative")
        .to_u64_digits();
    let canonical = Uint::new(
        [
            words.first().copied().unwrap_or(0),
            words.get(1).copied().unwrap_or(0),
        ]
        .into(),
    );
    F128::new_with_cfg(canonical, field_config)
}

fn max_boolean_residual_bound(matrices: &ConstraintMatrices<BigInt>) -> BigUint {
    let row_sums = |matrix: &SparseMatrix<BigInt>| {
        let mut sums = vec![BigUint::default(); matrix.row_count()];
        for column in matrix.columns() {
            for (row, coefficient) in column {
                sums[row] += coefficient.magnitude();
            }
        }
        sums
    };
    let a = row_sums(matrices.a());
    let b = row_sums(matrices.b());
    let c = row_sums(matrices.c());
    a.into_iter()
        .zip(b)
        .zip(c)
        .map(|((a, b), c)| a * b + c)
        .max()
        .unwrap_or_default()
}

fn integer_relation_digest(
    matrices: &ConstraintMatrices<BigInt>,
    map: &PreparedVirtualMap,
) -> Result<[u8; 32], Sha256ConstraintError> {
    let mut hash = Hasher::new();
    hash.update(b"f2z/sha256/integer-relation/v1");
    hash.update(&map.digest());
    for (label, matrix) in
        [b'A', b'B', b'C']
            .into_iter()
            .zip([matrices.a(), matrices.b(), matrices.c()])
    {
        hash.update(&[label]);
        for value in [matrix.row_count(), matrix.column_count(), matrix.nnz()] {
            hash_usize(&mut hash, value)?;
        }
        for column in matrix.columns() {
            hash_usize(&mut hash, column.len())?;
            for (row, coefficient) in column {
                hash_usize(&mut hash, row)?;
                let (sign, magnitude) = coefficient.to_bytes_le();
                hash.update(&[match sign {
                    Sign::NoSign => 0,
                    Sign::Plus => 1,
                    Sign::Minus => 2,
                }]);
                hash_usize(&mut hash, magnitude.len())?;
                hash.update(&magnitude);
            }
        }
    }
    Ok(*hash.finalize().as_bytes())
}

fn hash_usize(hash: &mut Hasher, value: usize) -> Result<(), Sha256ConstraintError> {
    hash.update(
        &u64::try_from(value)
            .map_err(|_| Sha256ConstraintError::IntegerRelationTooLarge)?
            .to_le_bytes(),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use crypto_primitives::crypto_bigint_uint::Uint;

    use crate::f2map::VirtualMap;
    use crate::pcs::FQ_MOD;
    use crate::piop::spartan::profile::PrimePolicy;

    use super::*;

    const OTHER_TEST_PRIME: u128 = (1_u128 << 127) - 1;

    fn config(modulus: u128) -> <F128 as PrimeField>::Config {
        F128::make_cfg(&Uint::from(modulus)).expect("odd test modulus")
    }

    #[test]
    fn local_relation_has_the_freigen_geometry() {
        let prepared = prepare_sha256_compression_batch_for_test(3).unwrap();
        let matrices = prepared.project(&config(FQ_MOD)).unwrap();
        let map = prepared.map();
        let p_f = prepared.source_params();
        let p_h = prepared.assignment_params();
        assert_eq!(
            matrices.matrices().a().row_count(),
            SHA256_CONSTRAINT_STRIDE
        );
        assert_eq!(matrices.matrices().a().column_count(), SHA256_H_STRIDE);
        assert_eq!(matrices.num_row_vars(), SHA256_CONSTRAINT_LOCAL_VARS);
        assert_eq!(matrices.num_column_vars(), SHA256_H_LOCAL_VARS);
        assert_eq!(map.local().rows(), SHA256_H_BAR_LIVE_BITS);
        assert_eq!(map.local().cols(), SHA256_F_BAR_LIVE_BITS);
        assert_eq!(map.live_rows(), 1 + 8 * SHA256_H_INSTANCE_BITS);
        assert_eq!(map.live_cols(), 1 + 8 * SHA256_F_INSTANCE_BITS);
        assert_eq!(map.rows(), 1 << 18);
        assert_eq!(map.cols(), 1 << 16);
        assert_eq!(
            *p_f,
            IntEvalParams {
                t: 16,
                s: 0,
                word_bits: 1
            }
        );
        assert_eq!(
            *p_h,
            IntEvalParams {
                t: 18,
                s: 0,
                word_bits: 1
            }
        );
    }

    #[test]
    fn repeated_map_preserves_instance_coordinates() {
        let prepared = prepare_sha256_compression_batch_for_test(2).unwrap();
        let map = prepared.map();
        let instances = 4;
        for local_column in [1, SHA256_F_BAR_LIVE_BITS - 1] {
            let local_rows = map
                .local()
                .matrix()
                .column(local_column)
                .unwrap()
                .row_indices()
                .to_vec();
            for instance in 0..instances {
                let global_column = 1 + instance * SHA256_F_INSTANCE_BITS + local_column - 1;
                let global_rows = map.column_rows(global_column).unwrap().collect::<Vec<_>>();
                assert_eq!(
                    global_rows,
                    local_rows
                        .iter()
                        .map(|row| {
                            if *row == 0 {
                                0
                            } else {
                                1 + instance * SHA256_H_INSTANCE_BITS + row - 1
                            }
                        })
                        .collect::<Vec<_>>()
                );
            }
        }

        let constant_rows = map.column_rows(0).unwrap().collect::<Vec<_>>();
        let expected_constant_rows = map
            .local()
            .matrix()
            .column(0)
            .unwrap()
            .row_indices()
            .iter()
            .flat_map(|&row| {
                if row == 0 {
                    vec![0]
                } else {
                    (0..instances)
                        .map(|instance| 1 + instance * SHA256_H_INSTANCE_BITS + row - 1)
                        .collect()
                }
            })
            .collect::<Vec<_>>();
        assert_eq!(constant_rows, expected_constant_rows);
    }

    #[test]
    fn assignment_row_sizing_fills_one_global_domain_without_instance_padding() {
        let log_rows = 21;
        let prepared = prepare_sha256_compression_batch_for_assignment_rows(log_rows).unwrap();
        let domain = 1usize << log_rows;
        let instances = (domain - 1) / SHA256_H_INSTANCE_BITS;

        assert_eq!(instances, 102);
        assert_eq!(prepared.instances(), instances);
        assert_eq!(prepared.log_instance_capacity(), 7);
        assert_eq!(prepared.assignment_params().cells(), domain);
        assert_eq!(prepared.assignment_params().s, 0);
        assert_eq!(
            prepared.map().live_rows(),
            1 + instances * SHA256_H_INSTANCE_BITS
        );
        assert_eq!(
            prepared.map().live_cols(),
            1 + instances * SHA256_F_INSTANCE_BITS
        );
        assert!(domain - prepared.map().live_rows() < SHA256_H_INSTANCE_BITS);
        assert!(
            prepared
                .map()
                .column_rows(prepared.map().live_cols())
                .unwrap()
                .next()
                .is_none()
        );
    }

    #[test]
    fn public_preparation_rejects_unsupported_instance_capacities() {
        for exponent in [6, 17] {
            assert!(matches!(
                prepare_sha256_compression_batch(exponent),
                Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent {
                    actual
                }) if actual == exponent
            ));
        }

        assert!(matches!(
            prepare_sha256_compression_batch_for_assignment_rows(20),
            Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent { actual: 6 })
        ));
        assert!(matches!(
            prepare_sha256_compression_batch_for_assignment_rows(31),
            Err(Sha256ConstraintError::UnsupportedInstanceCapacityExponent { actual: 17 })
        ));
    }

    #[test]
    fn public_preparation_rejects_profiles_the_sha_backend_cannot_use() {
        struct OversizedLigeritoTarget;
        impl IopSecurityProfile for OversizedLigeritoTarget {
            const NAME: &'static str = "oversized-ligerito-target-test";
            const LAMBDA: u32 = 100;
            const PRIME_POLICY: PrimePolicy = PrimePolicy::SingleDerived;
            const LIGERITO_TARGET_BITS: usize = 129;
            const FOREST_ROUND_GRINDING_BITS: u32 = 0;
            const RING_SWITCH_GRINDING_BITS: u32 = 0;
        }

        struct TwoPrimeShaProfile;
        impl IopSecurityProfile for TwoPrimeShaProfile {
            const NAME: &'static str = "two-prime-sha-test";
            const LAMBDA: u32 = 100;
            const PRIME_POLICY: PrimePolicy = PrimePolicy::TwoFullWidthFingerprint;
            const LIGERITO_TARGET_BITS: usize = 100;
            const FOREST_ROUND_GRINDING_BITS: u32 = 0;
            const RING_SWITCH_GRINDING_BITS: u32 = 0;
        }

        assert!(matches!(
            prepare_sha256_compression_batch_with_profile::<OversizedLigeritoTarget>(7),
            Err(Sha256ConstraintError::UnsupportedLigeritoTargetBits { actual: 129 })
        ));
        assert!(matches!(
            prepare_sha256_compression_batch_with_profile::<TwoPrimeShaProfile>(7),
            Err(Sha256ConstraintError::PrimeProfile(
                Sha256PrimeError::ProfileStrategyMismatch
            ))
        ));
    }

    #[test]
    fn public_statement_layout_matches_the_local_map() {
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        let map = prepared.map();
        let mut sources_by_h = vec![Vec::new(); map.local().matrix().row_count()];
        for (f_column, column) in map.local().matrix().columns().enumerate() {
            for &h_column in column.row_indices() {
                sources_by_h[h_column].push(f_column);
            }
        }

        for word_slot in 0..SHA256_PUBLIC_WORDS {
            for bit in 0..SHA256_PUBLIC_WORD_BITS {
                let h_column = sha256_public_h_column(word_slot, bit);
                let f_column = sha256_public_f_column(word_slot, bit);
                assert_eq!(sources_by_h[h_column], [f_column]);
            }
        }
    }

    #[test]
    fn integer_relation_projects_under_distinct_runtime_primes() {
        let prepared = prepare_sha256_compression_batch_for_test(3).unwrap();
        let fixed_config = config(FQ_MOD);
        let other_config = config(OTHER_TEST_PRIME);
        let fixed = prepared.project(&fixed_config).unwrap();
        let other = prepared.project(&other_config).unwrap();

        assert_eq!(
            fixed.field_modulus_encoding(),
            F128::canonical_modulus_encoding(&fixed_config)
        );
        assert_eq!(
            other.field_modulus_encoding(),
            F128::canonical_modulus_encoding(&other_config)
        );
        assert_ne!(fixed.digest(), other.digest());

        for (raw, fixed_matrix, other_matrix) in [
            prepared.local.matrices.a(),
            prepared.local.matrices.b(),
            prepared.local.matrices.c(),
        ]
        .into_iter()
        .zip([
            fixed.matrices().a(),
            fixed.matrices().b(),
            fixed.matrices().c(),
        ])
        .zip([
            other.matrices().a(),
            other.matrices().b(),
            other.matrices().c(),
        ])
        .map(|((raw, fixed), other)| (raw, fixed, other))
        {
            for ((raw_column, fixed_column), other_column) in raw
                .columns()
                .zip(fixed_matrix.columns())
                .zip(other_matrix.columns())
            {
                assert_eq!(raw_column.row_indices(), fixed_column.row_indices());
                assert_eq!(raw_column.row_indices(), other_column.row_indices());
                for ((raw_coefficient, fixed_coefficient), other_coefficient) in raw_column
                    .coefficients()
                    .iter()
                    .zip(fixed_column.coefficients())
                    .zip(other_column.coefficients())
                {
                    assert_eq!(
                        fixed_coefficient,
                        &bigint_to_field(raw_coefficient, &BigInt::from(FQ_MOD), &fixed_config,)
                    );
                    assert_eq!(
                        other_coefficient,
                        &bigint_to_field(
                            raw_coefficient,
                            &BigInt::from(OTHER_TEST_PRIME),
                            &other_config,
                        )
                    );
                }
            }
        }

        let same_relation = prepare_sha256_compression_batch_for_test(0).unwrap();
        assert_eq!(
            prepared.integer_relation_digest(),
            same_relation.integer_relation_digest()
        );
    }

    #[test]
    fn boolean_residual_bound_is_below_the_smallest_production_prime() {
        let prepared = prepare_sha256_compression_batch_for_test(0).unwrap();
        assert!(prepared.max_boolean_residual_bound() < &(BigUint::from(1_u8) << 111));
    }
}
