//! Public SHA-256 compression constraints and their batch geometry.
//!
//! The symbolic circuit is replayed exactly once. Its local CSC matrices are
//! retained once, while independent compression batches are represented by a
//! tensor repetition over the instance coordinate.

use std::sync::OnceLock;

use circuit::{
    constraints::{ConstraintGenerator, SparseMatrix as CircuitSparseMatrix},
    sha256::{compression_circuit, COMPRESSION_INPUT_BITS},
};
use crypto_primitives::{crypto_bigint_monty::F128, crypto_bigint_uint::Uint, PrimeField};
use num_bigint::{BigInt, Sign};
use thiserror::Error;

use crate::{
    f2map::{PreparedVirtualMap, PreparedVirtualMapError, RepeatedVirtualMap},
    pcs::{IntEvalParams, FQ_MOD},
    sparse_matrix::SparseMatrix,
};

use super::super::{
    f2z::{spartan_f2z_field_config, SpartanF2zField},
    ConstraintMatrices, PreparedConstraintMatrices, SpartanMatrixError,
};

/// Live Boolean source bits generated by one compression.
pub const SHA256_F_LIVE_BITS: usize = 7_144;
/// Source bits after adding the public constant-one coordinate.
pub const SHA256_F_BAR_LIVE_BITS: usize = SHA256_F_LIVE_BITS + 1;
/// Padded source stride used by the committed bit grid.
pub const SHA256_F_STRIDE: usize = 1 << SHA256_F_LOCAL_VARS;
/// Local source-coordinate width.
pub const SHA256_F_LOCAL_VARS: usize = 13;

/// Live integer-assignment bits, including its leading constant one.
pub const SHA256_H_BAR_LIVE_BITS: usize = 20_457;
/// Padded Spartan-assignment stride.
pub const SHA256_H_STRIDE: usize = 1 << SHA256_H_LOCAL_VARS;
/// Local assignment-coordinate width.
pub const SHA256_H_LOCAL_VARS: usize = 15;

/// Live rank-1 constraints generated by one compression.
pub const SHA256_CONSTRAINTS: usize = 184;
/// Padded constraint-row stride.
pub const SHA256_CONSTRAINT_STRIDE: usize = 1 << SHA256_CONSTRAINT_LOCAL_VARS;
/// Local constraint-row coordinate width.
pub const SHA256_CONSTRAINT_LOCAL_VARS: usize = 8;

/// Failures while compiling or repeating the public SHA-256 relation.
#[derive(Debug, Error)]
pub enum Sha256ConstraintError {
    /// The requested power-of-two batch does not fit the host index type.
    #[error("SHA-256 compression exponent is too large")]
    InvalidBatchExponent,

    /// Generated R1CS matrices did not prepare successfully.
    #[error(transparent)]
    Spartan(#[from] SpartanMatrixError),

    /// Generated Boolean map metadata did not prepare successfully.
    #[error(transparent)]
    VirtualMap(#[from] PreparedVirtualMapError),
}

type LocalRelation = (
    PreparedConstraintMatrices<SpartanF2zField>,
    PreparedVirtualMap,
);

static LOCAL_RELATION: OnceLock<LocalRelation> = OnceLock::new();

/// Prepares the public relation for `2^log_compressions` independent SHA-256
/// compression invocations.
///
/// The returned Spartan matrices are the one-compression local matrices. The
/// batch repetition is implicit in the returned map and in the two F2Z
/// geometries; the SHA proof adapter applies the same tensor structure to the
/// local `A/B/C` matrices without materializing global CSC offsets.
pub fn prepare_sha256_compression_batch(
    log_compressions: usize,
) -> Result<
    (
        PreparedConstraintMatrices<SpartanF2zField>,
        RepeatedVirtualMap,
        IntEvalParams,
        IntEvalParams,
    ),
    Sha256ConstraintError,
> {
    let instances = 1usize
        .checked_shl(
            u32::try_from(log_compressions)
                .map_err(|_| Sha256ConstraintError::InvalidBatchExponent)?,
        )
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;
    SHA256_H_STRIDE
        .checked_mul(instances)
        .ok_or(Sha256ConstraintError::InvalidBatchExponent)?;

    let (local_matrices, local_map) = local_relation();
    let map = RepeatedVirtualMap::new(local_map.clone(), instances)?;
    let p_f = IntEvalParams {
        t: log_compressions,
        s: SHA256_F_LOCAL_VARS,
        word_bits: 1,
    };
    let p_h = IntEvalParams {
        t: log_compressions,
        s: SHA256_H_LOCAL_VARS,
        word_bits: 1,
    };
    Ok((local_matrices.clone(), map, p_f, p_h))
}

fn local_relation() -> &'static LocalRelation {
    LOCAL_RELATION.get_or_init(|| {
        build_local_relation().expect("the static SHA-256 compression relation is valid")
    })
}

fn build_local_relation() -> Result<LocalRelation, Sha256ConstraintError> {
    let mut generator = ConstraintGenerator::new(COMPRESSION_INPUT_BITS);
    let inputs = generator.inputs();
    let _ = compression_circuit(&mut generator, &inputs);
    let generated = generator.into_matrices();

    assert_eq!(generated.m.row_count(), SHA256_H_BAR_LIVE_BITS);
    assert_eq!(generated.m.column_count(), SHA256_F_BAR_LIVE_BITS);
    assert_eq!(generated.a.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.b.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.c.row_count(), SHA256_CONSTRAINTS);
    assert_eq!(generated.a.column_count(), SHA256_H_BAR_LIVE_BITS);

    let field_config = spartan_f2z_field_config();
    let a = convert_r1cs_matrix(&generated.a, &field_config)?;
    let b = convert_r1cs_matrix(&generated.b, &field_config)?;
    let c = convert_r1cs_matrix(&generated.c, &field_config)?;
    let matrices =
        PreparedConstraintMatrices::new(ConstraintMatrices::new(a, b, c)?, &field_config)?;

    let mut map_rows = generated
        .m
        .rows()
        .iter()
        .map(|row| {
            row.positions()
                .iter()
                .copied()
                .map(|column| (column, true))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    map_rows.resize_with(SHA256_H_STRIDE, Vec::new);
    let map =
        SparseMatrix::try_from_rows(SHA256_F_STRIDE, map_rows).map_err(SpartanMatrixError::from)?;
    let map = PreparedVirtualMap::new(map)?;

    Ok((matrices, map))
}

fn convert_r1cs_matrix(
    matrix: &CircuitSparseMatrix<BigInt>,
    field_config: &<F128 as PrimeField>::Config,
) -> Result<SparseMatrix<F128>, SpartanMatrixError> {
    debug_assert!(matrix.row_count() <= SHA256_CONSTRAINT_STRIDE);
    debug_assert!(matrix.column_count() <= SHA256_H_STRIDE);

    let mut rows = matrix
        .rows()
        .iter()
        .map(|row| {
            row.entries()
                .iter()
                .map(|(column, coefficient)| (*column, bigint_to_field(coefficient, field_config)))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    rows.resize_with(SHA256_CONSTRAINT_STRIDE, Vec::new);
    SparseMatrix::try_from_rows(SHA256_H_STRIDE, rows).map_err(SpartanMatrixError::from)
}

fn bigint_to_field(value: &BigInt, field_config: &<F128 as PrimeField>::Config) -> F128 {
    let modulus = BigInt::from(FQ_MOD);
    let mut reduced = value % &modulus;
    if reduced.sign() == Sign::Minus {
        reduced += &modulus;
    }
    let words = reduced
        .to_biguint()
        .expect("a reduced coefficient is nonnegative")
        .to_u64_digits();
    let canonical = Uint::new(
        [
            words.first().copied().unwrap_or(0),
            words.get(1).copied().unwrap_or(0),
        ]
        .into(),
    );
    F128::new_with_cfg(canonical, field_config)
}

#[cfg(test)]
mod tests {
    use crate::f2map::VirtualMap;

    use super::*;

    #[test]
    fn local_relation_has_the_freigen_geometry() {
        let (matrices, map, p_f, p_h) = prepare_sha256_compression_batch(3).unwrap();
        assert_eq!(
            matrices.matrices().a().row_count(),
            SHA256_CONSTRAINT_STRIDE
        );
        assert_eq!(matrices.matrices().a().column_count(), SHA256_H_STRIDE);
        assert_eq!(matrices.num_row_vars(), SHA256_CONSTRAINT_LOCAL_VARS);
        assert_eq!(matrices.num_column_vars(), SHA256_H_LOCAL_VARS);
        assert_eq!(map.local().rows(), SHA256_H_STRIDE);
        assert_eq!(map.local().cols(), SHA256_F_STRIDE);
        assert_eq!(map.rows(), 8 * SHA256_H_STRIDE);
        assert_eq!(map.cols(), 8 * SHA256_F_STRIDE);
        assert_eq!(
            p_f,
            IntEvalParams {
                t: 3,
                s: 13,
                word_bits: 1
            }
        );
        assert_eq!(
            p_h,
            IntEvalParams {
                t: 3,
                s: 15,
                word_bits: 1
            }
        );
    }

    #[test]
    fn repeated_map_preserves_instance_coordinates() {
        let (_, map, _, _) = prepare_sha256_compression_batch(2).unwrap();
        let instances = 4;
        for local_column in [0, 1, SHA256_F_BAR_LIVE_BITS - 1] {
            let local_rows = map
                .local()
                .matrix()
                .column(local_column)
                .unwrap()
                .row_indices()
                .to_vec();
            for instance in 0..instances {
                let global_column = local_column * instances + instance;
                let global_rows = map.column_rows(global_column).unwrap().collect::<Vec<_>>();
                assert_eq!(
                    global_rows,
                    local_rows
                        .iter()
                        .map(|row| row * instances + instance)
                        .collect::<Vec<_>>()
                );
            }
        }
    }
}
